### ISSUE TITLE
readme.

### ISSUE THREAD

**Issue by remarco** [Lu-Yi-Hsun/iqoptionapi#1]
I think you must change readme and need update it with your new options.

**Comment by Lu-Yi-Hsun** [comment]
Ok I will fix it today

**Comment by Lu-Yi-Hsun** [comment]
@remarco  i add more thing

**Comment by Lu-Yi-Hsun** [comment]
@remarco fix

**Comment by remarco** [comment]
nice:)

**Comment by remarco** [comment]
i tray on 2.7 its work...
