### ISSUE TITLE
API on Windows

### ISSUE THREAD

**Issue by sampyz** [Lu-Yi-Hsun/iqoptionapi#10]
Hello guys,

someone can help me to use this api on windows?

Thanks

**Comment by milteven12** [comment]
What is your error?
It works fine here.

**Comment by Lu-Yi-Hsun** [comment]
install python
https://www.youtube.com/watch?v=3lGhtIqT0Tk

**Comment by sampyz** [comment]
Hi milteven and thanks for your reply,

I dont know how to use with python for windows..can u give me some example???

I have to use with console?

**Comment by sampyz** [comment]
Thanks Lu-Yi-Hsun,
Tomorrow i try to do that...i need to integrate your api to my bot writed on autoit.

I hope i can do that...

**Comment by remarco** [comment]
no resonable use autoit with this api. in this api is all you need for work.
