### ISSUE TITLE
Identation problem

### ISSUE THREAD

**Issue by glira** [Lu-Yi-Hsun/iqoptionapi#102]
Hello Lu, please fix wrong identation in 
https://github.com/Lu-Yi-Hsun/iqoptionapi/blob/master/iqoptionapi/ws/chanels/api_game_betinfo.py
line 15
thank!

**Comment by Lu-Yi-Hsun** [comment]
@glira  get_betinfo() is working!
it only can call get_betinfo, when the order is close!

if the order is open.get_betinfo()will return None
