### ISSUE TITLE
Disconnect implementation

### ISSUE THREAD

**Issue by glira** [Lu-Yi-Hsun/iqoptionapi#103]
Hi Lu, i am here again, i want known how is best mode to implement one disconnection ? 
i thinking in give one delay between some traders so i want disconnect by some hours and connect again after.

**Comment by Lu-Yi-Hsun** [comment]
@glira sorry I do not know your poblem

**Comment by glira** [comment]
I need disconnect api(my connection) of iqoption and connect after one time you understand? 
what you recommendation?

**Comment by JafferWilson** [comment]
@glira Why do you need a disconnect? You can always connect or reconnect if the server is closed using the `I_want_money.connect()` function.
