### ISSUE TITLE
Help "ERROR:root:**error** connect() fail"

### ISSUE THREAD

**Issue by AlphaCeph-Physics** [Lu-Yi-Hsun/iqoptionapi#104]
Hello everyone, i`m noob in python. I am having this problem with the code, I tried to uninstall and install as readme websocket, but did not have a good result. The code cannot connect to the IQ Option. I want to use this code just to get the candles, and I will analyze my strategies in Matlab. Can someone help me?
![iq](https://user-images.githubusercontent.com/54855097/64191066-0b11d600-ce4e-11e9-844b-0ec168380adf.png)

**Comment by JafferWilson** [comment]
You are giving the wrong credential to the API. Try t login with the same copy pasted in your browser. You will understand.

**Comment by AlphaCeph-Physics** [comment]
This is not the problem, I have tested several times.

**Comment by AlphaCeph-Physics** [comment]
For some reason, I redo the download and replace it in the folder, now everything works! Thks!
