### ISSUE TITLE
Issues with the Binary option Profits

### ISSUE THREAD

**Issue by JafferWilson** [Lu-Yi-Hsun/iqoptionapi#106]
Hi Lu,
I have found something weird with the API.
When I tried this code for getting the profits of the option, I received the turbo and binary percentage return.
```
>>> I_want_money=IQ_Option(email,password)
>>> d = I_want_money.get_all_profit()
>>> d['GBPCAD']
defaultdict(<class 'dict'>, {'turbo': 0.85, 'binary': 0.82})
```

But the problem is Turbo for that currency is not available. Only Binary is available now. Tell me what I can do. See the screenshot:
![image](https://user-images.githubusercontent.com/13446197/64356887-3f89bb80-d021-11e9-94fe-72cf910ee812.png)

**Comment by Lu-Yi-Hsun** [comment]
@JafferWilson  https://github.com/Lu-Yi-Hsun/iqoptionapi#check-asset-if-open-or-not

**Comment by JafferWilson** [comment]
@Lu-Yi-Hsun Thank you Lu. I will check that will revert back to you
