### ISSUE TITLE
error executing buy version 3.9.1

### ISSUE THREAD

**Issue by josemaramorim** [Lu-Yi-Hsun/iqoptionapi#111]
**VERSION PYTHON:**
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**CODE:**

goal = 'EURUSD'
duration = 1  # minute 1 or 5
amount = 1
buy = "call"  # or "put"
id_number = iqoption.buy(amount, goal, buy, duration)
print(id_number)

**ERROR:**
  File "C:\Users\AMORIM-NOTE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\iqoptionapi\stable_api.py", line 662, in buy
    self.api.buy(price, OP_code.ACTIVES[ACTIVES], ACTION, expirations)
  File "C:\Users\AMORIM-NOTE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\iqoptionapi\ws\chanels\buyv2.py", line 25, in __call__
    exp,idx=get_expiration_time(int(self.api.timesync.server_timestamp),duration)
  File "C:\Users\AMORIM-NOTE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\iqoptionapi\expiration.py", line 11, in get_expiration_time
    if (int((exp_date+timedelta(minutes=1)).strftime("%s"))-timestamp)>30:
ValueError: Invalid format string

**Comment by guilhersantos** [comment]
I also have the same problem.

**Comment by josemaramorim** [comment]
@guilhersantos Are you Brazilian?

**Comment by guilhersantos** [comment]
Sim
________________________________
De: josemaramorim <notifications@github.com>
Enviado: quarta-feira, 11 de setembro de 2019 10:36:03
Para: Lu-Yi-Hsun/iqoptionapi <iqoptionapi@noreply.github.com>
Cc: guilhersantos <guilhermeshs1@outlook.com>; Mention <mention@noreply.github.com>
Assunto: Re: [Lu-Yi-Hsun/iqoptionapi] error executing buy version 3.9.1 (#111)


@guilhersantos<https://github.com/guilhersantos> Are you Brazilian?

**Comment by Lu-Yi-Hsun** [comment]
I check now

**Comment by josemaramorim** [comment]
@Lu-Yi-Hsun - Hello would you like to send me an email so we can talk I'm looking for a python programmer to develop an application using this API, I'm developing but I don't have much knowledge in python and I'm having a hard time.
This invitation is also extended to other programmers I leave here my email so you can contact josemaramorim@yahoo.com.br put the subject "API IQOPTION"

**Comment by Lu-Yi-Hsun** [comment]
buy() api I can work in Linux.. I can not rebuild the bug

**Comment by josemaramorim** [comment]
I am working on windows 10

**Comment by josemaramorim** [comment]
The problem is in this excerpt of the code, I went to look for and the solution would be to change the "% s" for "% S", but it worked in while and does not exit.

while index <idx:
         if int (exp_date.strftime ("% M"))% 15 == 0 and (int (exp_date.strftime ("% S")) - int (timestamp))> 60 * 5:
             exp.append (exp_date.strftime ("% S"))
             index = index + 1
         exp_date = exp_date + timedelta (minutes = 1)

**Comment by Lu-Yi-Hsun** [comment]
@josemaramorim @guilhersantos fix! 3.9.2 can support window10

**Comment by Lu-Yi-Hsun** [comment]
> @Lu-Yi-Hsun - Hello would you like to send me an email so we can talk I'm looking for a python programmer to develop an application using this API, I'm developing but I don't have much knowledge in python and I'm having a hard time.
> This invitation is also extended to other programmers I leave here my email so you can contact [josemaramorim@yahoo.com.br](mailto:josemaramorim@yahoo.com.br) put the subject "API IQOPTION"

ok sent you

**Comment by josemaramorim** [comment]
I did the tests here and it all worked out thank you all.

**Comment by guilhersantos** [comment]
what you did to work, mine here hasn't worked yet.

ERROR:root:check buy_successful time late 60sec
None
