### ISSUE TITLE
API is not placing trades

### ISSUE THREAD

**Issue by AjayKush114** [Lu-Yi-Hsun/iqoptionapi#116]
Hello sir,

i am using the current update of this version of API, At start it was working fine, But from past two days the API has stopped placing binary trades on Iqoption.

Note:- i am using the sample from your example to place trades on IQ

I_Want_Money = IQ_Option(Email, Password)
goal = "EURUSD"
#print("get candles")
#print(I_Want_Money.get_candles(goal, 60, 111, time.time()))
print(I_Want_Money.get_balance())
Money = 1
ACTIVES = "EURUSD"
ACTION = "call" # or "put"
expirations_mode = 1
force_buy = False # i suggest use False
print(str(I_Want_Money.buy(Money, ACTIVES, ACTION, expirations_mode, force_buy)))

Please guide me to solve this issue.

Thanks,
Ajay

**Comment by Lu-Yi-Hsun** [comment]
The buy api is change.

Please deleted force_buy

**Comment by AjayKush114** [comment]
ok sir

**Comment by AjayKush114** [comment]
i have downloaded the updated and now i am making changes,

Will test it and let you know.

Thanks for your prompt reply

**Comment by SOFTWAREAMAL** [comment]
Sir, Kindly send me latest IQ Option API, 

because following program  not taking Trade
from iqoptionapi.stable_api import IQ_Option
iq = IQ_Option("xxx@xxx", "xxxxx")
iq.buy(100, "AUDUSD", "call", 1)
