### ISSUE TITLE
How to check if the digital pair is open?

### ISSUE THREAD

**Issue by guilhersantos** [Lu-Yi-Hsun/iqoptionapi#118]
How to check if the digital pair is open?
And how to see the payout and get the current candles?

**Comment by JafferWilson** [comment]
@guilhersantos Please read the Read.me file. And close this question,it is not an issue with the API.

**Comment by guilhersantos** [comment]
@JafferWilson  I need something like this, only for digital. In the readme I found nothing similar.


from iqoptionapi.stable_api import IQ_Option
binary=IQ_Option("email","passwd")
init_info=binary.get_all_init()
profit = binary.get_all_profit()
OP_code = binary.get_all_ACTIVES_OPCODE()

pares = ['AUDJPY', 'EURJPY', 'NZDUSD', 'EURUSD', 'AUDUSD', 'EURAUD', 'USDJPY', 'EURCAD', 'GBPCAD', 'AUDCAD', 'USDCHF', 'EURGBP', 'USDCAD', 'GBPUSD','EURUSD-OTC','EURGBP-OTC','USDCHF-OTC','NZDUSD-OTC', 'AUDCAD-OTC']

lista = []
for listpar in pares:
    if init_info["result"]["turbo"]["actives"][str(OP_code[listpar])]["enabled"] ==True:
        print('Par:',listpar,' Payout:',(str(profit[listpar]["turbo"]))," Status:open")
        
print (init_info)
