### ISSUE TITLE
Not able to check the Assets are opened or not in real time.

### ISSUE THREAD

**Issue by JafferWilson** [Lu-Yi-Hsun/iqoptionapi#122]
I have found issues using the function for checking the asset open or not
`ALL_Asset=I_want_money.get_all_open_time()`
You see this image:

![image](https://user-images.githubusercontent.com/13446197/65407645-d9fb4480-de00-11e9-9f15-ff1e5237b8d9.png)
Binary not available but turbo available
but the api response is:
```
>>> print(ALL_Asset["binary"]["GBPNZD"]["open"]
... )
True
>>> print(ALL_Asset["turbo"]["GBPNZD"]["open"])
True
```
Also when I tested for the currency: USD/NOK , turbo not available binary available. I get response from api:
```
>>> print(ALL_Asset["turbo"]["USDNOK"]["open"])
{}
>>> print(ALL_Asset["binary"]["USDNOK"]["open"])
True
```
![image](https://user-images.githubusercontent.com/13446197/65407711-fdbe8a80-de00-11e9-9ba0-84eb4aa3ba1f.png)

Please check this

API version: Version 3.9.2
Python version : Python 3.5.0
OS Version: Windows 10.

**Comment by Lu-Yi-Hsun** [comment]
@JafferWilson i need log file.

**Comment by JafferWilson** [comment]
@Lu-Yi-Hsun Hi Lu, thank you for your response.
Let me tell you. I did not get any error or anything in the debugging. It was simply something from the inside. I tried to check the values for the binary option, when they were available and wen they were not.
So I found this bug in the implementation. Please can you check it once on your side. Check it when the option currency is available for 1 minute and when it is not. You will see the same error. Please let me know if anything else to explain.

**Comment by Lu-Yi-Hsun** [comment]
fix

**Comment by JafferWilson** [comment]
I guess it will work. I will test it. But I will close this issue for now. Thank you @Lu-Yi-Hsun .
