### ISSUE TITLE
403 Client Error: Forbidden for url: https://auth.iqoption.com/api/v1.0/login

### ISSUE THREAD

**Issue by greatzg** [Lu-Yi-Hsun/iqoptionapi#138]
> 2019-11-03 14:37:04,813 https://auth.iqoption.com/api/v1.0/login
> 2019-11-03 14:37:04,814 Starting new HTTPS connection (1): auth.iqoption.com:443
> 2019-11-03 14:37:05,712 https://auth.iqoption.com:443 "POST /api/v1.0/login HTTP/1.1" 403 55
> 2019-11-03 14:37:05,713 <Response [403]>
> 2019-11-03 14:37:05,713 {"errors":[{"code":202,"title":"Invalid credentials"}]}
> 2019-11-03 14:37:05,713 {'Server': 'nginx', 'Date': 'Sun, 03 Nov 2019 07:37:06 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '55', 'Connection': 'keep-alive', 'Vary': 'Origin', 'X-Tracing-Key': '87984a97-4d97-4156-99fc-7e6e56019664'}
> 2019-11-03 14:37:05,713 <RequestsCookieJar[]>
> 2019-11-03 14:37:05,714 403 Client Error: Forbidden for url: https://auth.iqoption.com/api/v1.0/login

Howt could I do?

**Comment by kkagill** [comment]
Based on your error, your credentials are invalid. Can you try matching them correctly? Try logging in iq option web site first.

**Comment by greatzg** [comment]
> Based on your error, your credentials are invalid. Can you try matching them correctly? Try logging in iq option web site first.

`email = "sample@samplemail.com"
pwd = "samplepassword"

I_want_money = IQ_Option(email, pwd)
I_want_money.set_max_reconnect(-1)  # allow unlimited reconnect
while True:
    # you can !!close yuor network!! to simulation network fails
    if I_want_money.check_connect() is False:  # detect the websocket is close
        print("try reconnect")
        I_want_money.connect()  # try to connect
        print("reconnect Success")
    time.sleep(1)`

I use email and password like this. Is this correct? Because I can still logged in by the same email and password in my code.

**Comment by Lu-Yi-Hsun** [comment]
@greatzg  password or email not correctly.

i think you reconnect too many time  iqoption server ban you ip "Client Error: Forbidden for url"

Can you log in to the iqoption "Web Page"?

**Comment by greatzg** [comment]
I changed to use a new email and problem is fix.
