### ISSUE TITLE
buy_digital_spot not working

### ISSUE THREAD

**Issue by kkagill** [Lu-Yi-Hsun/iqoptionapi#139]
Hi,

So I simply tried with `buy_digital_spot` with OTC asset, and I just got an error below.

```from iqoptionapi.stable_api import IQ_Option
import time
import logging
import random
logging.basicConfig(level=logging.DEBUG,format='%(asctime)s %(message)s')
I_want_money=IQ_Option("","")
ACTIVES="EURUSD-OTC"
duration=1#minute 1 or 5
amount=1
action="call"#put
from datetime import datetime
 
id=I_want_money.buy_digital_spot(ACTIVES,amount,action,duration) 
print(id)
```

```2019-11-03 01:09:38,409 {"name": "sendMessage", "msg": {"name": "digital-options.place-digital-option", "version": "1.0", "body": {"user_balance_id": 244496972, "instrument_id": "doEURUSD-OTC201911030910PT1MCSPT", "amount": "1"}}, "request_id": ""}
2019-11-03 01:09:38,590 {"name":"result","request_id":"","msg":{"success":true}}
2019-11-03 01:09:38,768 {"request_id":"","name":"digital-option-placed","msg":{"message":"quotesApplication.ConsumeQuoteByTime: invalid instrument: doEURUSD-OTC201911030910PT1MCSPT"},"status":5000}```

Can you take a look at this please?

**Comment by kkagill** [comment]
wow this is so weird! 
I tried 10 times in a row and it threw me with 'error' message.
and now it works.
Thanks anyways!

**Comment by Lu-Yi-Hsun** [comment]
@kkagill 
buy_digital_spot can not work in anytime? what your version?
in my test it can work.

only your time is too close to the Purchase time 

for example in your computer Purchase time is 0.5 sec, and you sent buy message to iqoption Server,
because of network and process delay,when iqoption Server get the buy mesage Purchase time is 0 sec.

so you get error

**Comment by rochapedro07** [comment]
eu tbm estou com o msm problema, um dia o codigo estava fucionado e em outro nao fuciona mas; 1 erro -Cannot purchase an option (active is suspended). 2 erro - fica falando a os bares nao estao aberto para negociacoes. 
from iqoptionapi.stable_api import IQ_Option
import time
from datetime import datetime , timedelta

email = "************"
senha = '***********'

API = IQ_Option(email , senha)

check , reason = API.connect()

if check:
    print('Conectado com sucesso')
else:
    if reason == '{"code":"invalid_credentials","message":"You entered the wrong credentials. Please ensure that your login/password is correct."}':
        print('Email ou senha incorreta')
    else:
        print('Houve um problema na conexão')
        print(reason)
    exit()  # Encerra o programa se a conexão falhar

while True:
    escolha = input('Selecione a conta em que deseja conectar: demo ou real  - ')
    if escolha == 'demo':
        conta = 'PRACTICE'
        print('Conta demo selecionada')
        break
    if escolha == 'real':
        conta = 'REAL'
        print('Conta real selecionada')
        break
    else:
        print('Escolha incorreta! Digite demo ou real')

API.change_balance(conta)


def compra(ativo, valor, direcao, exp, tipo):
    if tipo == 'digital':
        # Verifica se o ativo digital está disponível para negociação antes de tentar comprar
        available_assets = API.get_all_open_time()
        if available_assets:
            if 'digital' in available_assets and ativo in available_assets['digital']:
                is_active = available_assets['digital'][ativo]['open']
                if is_active:
                    # Determina o modo de expiração com base no tempo de expiração (exp) em minutos
                    if exp == 1:
                        expirations_mode = 1  # 1 Minuto
                    elif exp == 5:
                        expirations_mode = 5  # 5 Minutos
                    else:
                         print("Tempo de expiração não suportado para digital. Use 1 ou 5 minutos.")
                         return

                    check, id = API.buy_digital_spot_v2(ativo, valor, direcao, expirations_mode)
                else:
                    print(f'Erro: Ativo Digital {ativo} está suspenso para negociação.')
                    return
            else:
                print(f'Erro: Ativo Digital {ativo} não está disponível para negociação.')
                return
        else:
            print(f"Erro ao verificar disponibilidade do ativo digital: {available_assets}")
            return
    elif tipo == 'binaria':
        check, id = API.buy(valor, ativo, direcao, exp)
    else:
        print('Tipo de operação não reconhecida, escolha digital ou binaria')
        return

    if check:
        print('Ordem executada ', id)

        while True:
            time.sleep(0.1)
            if tipo == 'digital':
                result = API.check_win_digital(id , polling_time=1)
                if isinstance(result, tuple):  # Verifica se o retorno é uma tupla
                    status, resultado = result
                else:
                    print(f'Erro ao verificar resultado da ordem digital: {result}')
                    break  # Sai do loop interno se não conseguir pegar o resultado
            elif tipo == 'binaria':
                status, resultado = API.check_win_v4(id)
            else:
                print('Tipo de operação não reconhecida, escolha digital ou binaria')
                return
            if status:
                if resultado > 0:
                    print('WIN', round(resultado, 2))
                elif resultado == 0:
                    print('EMPATE', round(resultado, 2))
                else:
                    print('LOSS', round(resultado, 2))
                break
    else:
        print('erro na abertura da ordem,', id)


# Configurações da operação
ativo = 'EURUSD'
valor = 3
direcao = 'put'
exp = 1  # Expiração em minutos (1 ou 5) para digital, qualquer valor em minutos para binaria.
tipo = 'digital'

# Loop de entradas automáticas
while True:
    inicio_tempo = datetime.now()
    print(f"Iniciando nova entrada às {inicio_tempo.strftime('%H:%M:%S')}")
    compra(ativo, valor, direcao, exp, tipo)

    # Calcula o tempo para a próxima entrada
    proxima_entrada = inicio_tempo.replace(second=0, microsecond=0) + timedelta(minutes=1)
    tempo_espera = (proxima_entrada - datetime.now()).total_seconds()

    if tempo_espera > 0:
        print(f'Aguardando {int(tempo_espera)} segundos até a proxima entrada')
        time.sleep(tempo_espera)
