### ISSUE TITLE
OTC Candles

### ISSUE THREAD

**Issue by rajeshdua123** [Lu-Yi-Hsun/iqoptionapi#146]
Hi Lu,

How are you doing?  We are progressing on our project faster and have managed to complete 90% of it.  I will be sharing more updates with you once completed. 

In the meantime, can you please help me with the candle data of OTC market? 

Thanks and regards,
Rajesh

**Comment by Lu-Yi-Hsun** [comment]
OTC candle just use get candle or get real-time candle

**Comment by rajeshdua123** [comment]
I tried the following - 

data=I_want_money.get_candles("EURUSD", 60, 1000, end_from_time)

It returned the unix time stamp - 1573250400 which is Friday, November 8, 2019 10:00:00 PM

It is returning data of the last day only.  Not the current OTC. :(

Please guide me.

**Comment by Lu-Yi-Hsun** [comment]
“EURUSD-OTC”

**Comment by rajeshdua123** [comment]
Thank you Lu.

This works. :)
