### ISSUE TITLE
get_realtime_candles cannot get realtime data after a while

### ISSUE THREAD

**Issue by Phinox** [Lu-Yi-Hsun/iqoptionapi#149]
1.In a loop I use get_realtime_candles to get realtime data, the interval is 0.02s,After a while(about 1h),The return data  start to be same and don't change.
2.Restart the program ,sometimes It's Ok,after a while, the data begin to be same again.
3.Now I cannot login, use a different account,Try a different IP .The problem still exist.
Please Help .Thanks. I  imagine whether the key problem is my request frequency is to high(0.02 s ,12 thread for 12 different currency realtime data)? So the server banned me?

**Comment by Lu-Yi-Hsun** [comment]
this api is not thread safe,please use multiprocess

**Comment by JafferWilson** [comment]
You will need 12 different program for 12 different currencies. I had experimented a lot and found that the API do not work with threads.

**Comment by landimd** [comment]
> You will need 12 different program for 12 different currencies. I had experimented a lot and found that the API do not work with threads.

I got the same problem with threading to get data from different actives at the same time, making a different program to run for each pair was the solution for you? 
I did it before but it was consuming a lot of ram. 
Is there any other option?
