### ISSUE TITLE
get_candle doesn't stop properly.

### ISSUE THREAD

**Issue by zidokobik** [Lu-Yi-Hsun/iqoptionapi#151]
Whenever I try to stop a looped get_candle with Ctrl  + C within console this error shows up

![image](https://user-images.githubusercontent.com/56497400/69352756-5b424c80-0c75-11ea-9ca8-26ee6c0cc26d.png)
![image](https://user-images.githubusercontent.com/56497400/69352917-9fcde800-0c75-11ea-8bac-524a5a7971f2.png)

As you can see even after I press Ctrl + C, the loop doesn't actually stop. How do I stop the loop properly within console. I'm aware that Im not supposed to stream candles with get_candles().

**Comment by Lu-Yi-Hsun** [comment]
Same problem  with https://github.com/Lu-Yi-Hsun/iqoptionapi/issues/145

I will try to fix
