### ISSUE TITLE
Binary Options Buy Function Not Working

### ISSUE THREAD

**Issue by iagosantiago** [Lu-Yi-Hsun/iqoptionapi#163]
**Code**
> from iqoptionapi.stable_api import IQ_Option
> iq = IQ_Option("xxxxx@xxxxx.xxx", "xxxxx")
> iq.buy(100, "AUDUSD", "call", 1)

**Log**
ERROR:root:**warning** buy late 30 sec

(False, None)

DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520472400}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520473410}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520474420}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520475429}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520476440}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520477450}
DEBUG:iqoptionapi.ws.client:{"name":"heartbeat","msg":1575520477450}
DEBUG:iqoptionapi.api:{"name": "heartbeat", "msg": {"msg": {"heartbeatTime": 1575520477450, "userTime": 1575520477450}}, "request_id": ""}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520478458}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520479468}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520480477}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520481487}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520482495}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520483504}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520484513}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520485522}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520486534}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520487543}
DEBUG:iqoptionapi.ws.client:{"name":"heartbeat","msg":1575520487543}
DEBUG:iqoptionapi.api:{"name": "heartbeat", "msg": {"msg": {"heartbeatTime": 1575520487543, "userTime": 1575520487543}}, "request_id": ""}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520488552}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520489561}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520490571}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520491580}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520492591}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520493600}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520494609}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520495619}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520496627}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520497638}
DEBUG:iqoptionapi.ws.client:{"name":"heartbeat","msg":1575520497638}
DEBUG:iqoptionapi.api:{"name": "heartbeat", "msg": {"msg": {"heartbeatTime": 1575520497638, "userTime": 1575520497638}}, "request_id": ""}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520498648}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520499658}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520500667}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520501676}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520502685}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520503694}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520504704}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520505713}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520506721}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520507731}
DEBUG:iqoptionapi.ws.client:{"name":"heartbeat","msg":1575520507731}
DEBUG:iqoptionapi.api:{"name": "heartbeat", "msg": {"msg": {"heartbeatTime": 1575520507731, "userTime": 1575520507731}}, "request_id": ""}

**Comment by PoYuTsai** [comment]
@iagosantiago 
Sorry, the buy() function does not no longer supported anymore. (version 5.2.1)
 If you want to use the latest version, please email to the repository owner @Lu-Yi-Hsun. (yihsun1992@gmail.com).

**Comment by OverdriveNGain** [comment]
> **Code**
> 
> > from iqoptionapi.stable_api import IQ_Option
> > iq = IQ_Option("[xxxxx@xxxxx.xxx](mailto:xxxxx@xxxxx.xxx)", "xxxxx")
> > iq.buy(100, "AUDUSD", "call", 1)
> 
> **Log**
> ERROR:root:**warning** buy late 30 sec
> 
> (False, None)
> 
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520472400}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520473410}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520474420}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520475429}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520476440}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520477450}
> DEBUG:iqoptionapi.ws.client:{"name":"heartbeat","msg":1575520477450}
> DEBUG:iqoptionapi.api:{"name": "heartbeat", "msg": {"msg": {"heartbeatTime": 1575520477450, "userTime": 1575520477450}}, "request_id": ""}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520478458}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520479468}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520480477}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520481487}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520482495}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520483504}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520484513}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520485522}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520486534}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520487543}
> DEBUG:iqoptionapi.ws.client:{"name":"heartbeat","msg":1575520487543}
> DEBUG:iqoptionapi.api:{"name": "heartbeat", "msg": {"msg": {"heartbeatTime": 1575520487543, "userTime": 1575520487543}}, "request_id": ""}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520488552}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520489561}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520490571}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520491580}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520492591}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520493600}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520494609}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520495619}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520496627}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520497638}
> DEBUG:iqoptionapi.ws.client:{"name":"heartbeat","msg":1575520497638}
> DEBUG:iqoptionapi.api:{"name": "heartbeat", "msg": {"msg": {"heartbeatTime": 1575520497638, "userTime": 1575520497638}}, "request_id": ""}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520498648}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520499658}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520500667}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520501676}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520502685}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520503694}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520504704}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520505713}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520506721}
> DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1575520507731}
> DEBUG:iqoptionapi.ws.client:{"name":"heartbeat","msg":1575520507731}
> DEBUG:iqoptionapi.api:{"name": "heartbeat", "msg": {"msg": {"heartbeatTime": 1575520507731, "userTime": 1575520507731}}, "request_id": ""}

Same for me
