### ISSUE TITLE
How to make a sale?

### ISSUE THREAD

**Issue by fcatalan** [Lu-Yi-Hsun/iqoptionapi#17]
Hello, I would like to ask if there is a possibility that you can implement the sales service, to indicate that the low is the price and thus have the 2 options buying and selling. Can it be done now as is the API?

![image](https://user-images.githubusercontent.com/13498571/40848130-4acc446e-658c-11e8-9b6c-6e9aada4763a.png)

**Comment by Lu-Yi-Hsun** [comment]
```
from iqoptionapi.stable_api import IQ_Option
import logging
import time
logging.basicConfig(level=logging.DEBUG,format='%(asctime)s %(message)s')
I_want_money=IQ_Option("email","pass")
goal="EURUSD"
print("get candles")
print(I_want_money.get_candles(goal,60,111,time.time()))
Money=1
ACTIVES="EURUSD"
ACTION="call"
expirations_mode=1
force_buy= "True"
I_want_money.buy(Money,ACTIVES,ACTION,expirations_mode,force_buy)
```

**Comment by fcatalan** [comment]
Sometimes when you bet on binary operations you are asked to indicate if the price goes down or rises from the amount you indicate, in the API how do I manage that? How do I indicate that the operation I am doing isHigher or lower, 
As shown in the picture?

![image](https://user-images.githubusercontent.com/13498571/40862123-74e62f76-65b9-11e8-8adb-758df0279ca6.png)

**Comment by Lu-Yi-Hsun** [comment]
@fcatalan

from iqoptionapi.stable_api import IQ_Option
import logging
import time
logging.basicConfig(level=logging.DEBUG,format='%(asctime)s %(message)s')
I_want_money=IQ_Option("email","pass")
goal="EURUSD"
print("get candles")
print(I_want_money.get_candles(goal,60,111,time.time()))
Money=1
ACTIVES="EURUSD"
ACTION="call"
expirations_mode=1
force_buy= "True"
I_want_money.buy(Money,ACTIVES,ACTION,expirations_mode,force_buy)

**Comment by fcatalan** [comment]
@Lu-Yi-Hsun 

Thank you, so that my question is clearer, how can I tell the API that the purchase action is: Higher or Lower?, que parametro debo cambiar?

**Comment by Lu-Yi-Hsun** [comment]
```
Money=1
ACTIVES="EURUSD"
ACTION="call"#or "put"
#^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
expirations_mode=1
force_buy= "True"
I_want_money.buy(Money,ACTIVES,ACTION,expirations_mode,force_buy)
```

**Comment by fcatalan** [comment]
@Lu-Yi-Hsun 

thank you very much.
