### ISSUE TITLE
connect():DO you install right version?

### ISSUE THREAD

**Issue by Savalinn** [Lu-Yi-Hsun/iqoptionapi#18]
Hello, I got an error message while I try connect.

[https://ibb.co/hWuufy](https://ibb.co/hWuufy)

**Comment by Lu-Yi-Hsun** [comment]
@Savalinn 
you can try update last version ,i am not find that in last version

**Comment by Savalinn** [comment]
I always use the newest one... Hmm.. Without update I tried now, and now working well again.... I think it was temporaly problem....
