### ISSUE TITLE
Erro self.api.getprofile().json()

### ISSUE THREAD

**Issue by SilvaEngComp** [Lu-Yi-Hsun/iqoptionapi#185]
Hi! when I use the code in Jupter run right, but when I use in Pycharm or Spyder the json() method 
respon = self.api.getprofile().json(), in stable.py file, line 309,  not return and go to except. So it's back for conect() method. This stay in infinit loop. Can someone help me? Using the Jupter this not happen

**Comment by Lu-Yi-Hsun** [comment]
What api you using?

I think you are using low level api?

**Comment by SilvaEngComp** [comment]
How can I know what api I'm uising?  I folow this video tutorial:

 https://www.youtube.com/watch?v=Kt3ov6gGNZg&t=474s

**Comment by SilvaEngComp** [comment]
I'm using  5.1 version

**Comment by SilvaEngComp** [comment]
this is the code I'm try:

from iqoptionapi.stable_api import IQ_Option
import logging
import random
logging.basicConfig(level=logging.DEBUG,format='%(asctime)s %(message)s')
I_want_money=IQ_Option("my_email","my_passowrd")

So, it's connect, but not get the profile.  I have  debugged in PyCharm and saw the problem is in  json() method (respon = self.api.getprofile().json()), in stable.py file, line 309

**Comment by Lu-Yi-Hsun** [comment]
You can try private version .

**Comment by SilvaEngComp** [comment]
ok! Thank you!
