### ISSUE TITLE
check_win_v2 stopped working?

### ISSUE THREAD

**Issue by gstroligo** [Lu-Yi-Hsun/iqoptionapi#195]
Today check_win_v2 simply stopped working for me.. or has it stopped working for any body else too?

**Comment by gstroligo** [comment]
I was sending too many requests to IQ so it started returning none... so I changed stable api check_win_v2 interval so it would send a lot less of requests for checking order results.. if anyone has this problems try adding up interval on check_win_v2 func.. 

regards

**Comment by JafferWilson** [comment]
Please can you share the code with us? It will be helpful to understand. Plus the issue might be because of the use of the threads. The api is not supporting multi thread applications.
