### ISSUE TITLE
get_candles(self,count,ACTIVES)  need add time.

### ISSUE THREAD

**Issue by remarco** [Lu-Yi-Hsun/iqoptionapi#2]
at now you get candles 1s ???
if i need a minute 60s i need change funkcion?
is this is right?
maybe need rewrite this funkcion and add timeframe for candles .
like 1 =1s 60s = 1m etc...

**Comment by Lu-Yi-Hsun** [comment]
sorry my mother language is not english ~
yes ,interval  is  duration of candles.
i am change the code for more stable..and test the lib check "get_candles()" if stable or not

**Comment by remarco** [comment]
english is not my too :) its ok:)
maybe lib is stable but my code may not be. I'm not a pogrammer
bat originaly at time 1s they work well ... on longer time without errors.

**Comment by Lu-Yi-Hsun** [comment]
I find some problem "get_candles()" can not get the real time data(late 30sec)

**Comment by remarco** [comment]
oooh.... must be messages update candles or something like this.

**Comment by Lu-Yi-Hsun** [comment]
@remarco  
read  README.MD
fix candle stable
add get real time candle
put lib into iqoptionapi
....

**Comment by remarco** [comment]
I_want_money.get_candles(ACTIVES,interval,count,endtime)

i not understand what endtime?
how to count endtime???

**Comment by Lu-Yi-Hsun** [comment]
endtime: type(timestamp)
https://stackoverflow.com/questions/9637838/convert-string-date-to-timestamp-in-python

get candle have start time and end time
endtime mean
time
endtime-(candles count*interval)<--------------candles count---------endtime

**Comment by remarco** [comment]
whay wee cant calculate endtime from server time in get.candles function???
if not how to get server time ?

**Comment by Lu-Yi-Hsun** [comment]
@remarco 
endtime-(candles count*interval)<--------------candles count(here you want candles)--------------endtime
```
import time
st = time.strptime('2012-10-21 18:51:50', '%Y-%m-%d %H:%M:%S')
time.mktime(st)
```
