### ISSUE TITLE
'check_win_v2' it's not working in turbo and binary

### ISSUE THREAD

**Issue by jvddavid** [Lu-Yi-Hsun/iqoptionapi#201]
in my tests the 'check_win_v2', doesn't work due to the 'get_betinfo' function, there would be some alternative or correction.

**Comment by Alexandreoliveira** [comment]
@Lu-Yi-Hsun 
I couldn't make it work too!
Please help us

**Comment by Lu-Yi-Hsun** [comment]
In private version have v3

**Comment by supasitsst** [comment]
'get_betinfo()' it's not working too.

**Comment by jvddavid** [comment]
> In private version have v3

ok, i will buy as soon as i start selling my robot

**Comment by kkagill** [comment]
@jvddavid @Alexandreoliveira @supasitsst 

too bad people just don't search for solutions

https://github.com/Lu-Yi-Hsun/iqoptionapi/issues/196

**Comment by jvddavid** [comment]
@kkagill 
I am not looking for a solution because I am still learning python, and I do not have enough knowledge to create a solution, so once I learn and understand how the language works I will create a solution. I thank @Lu-Yi-Hsun for the work and effort in creating this api.

**Comment by kkagill** [comment]
@jvddavid you were looking for an alternative or correction which also means it's a solution. Anyways if you don't want my correction, I will tear it down.

**Comment by jvddavid** [comment]
hey @kkagill , I'm sorry if I went uneducated, I was stressed about other things, but I'm still looking for a solution or alternative. I didn't want to offend anyone. Sorry if I offended you.

**Comment by ItamarRocha** [comment]
anyone got this solved?
