### ISSUE TITLE
CONTRIBUTORS WITH DONATION TO FREE VERSION

### ISSUE THREAD

**Issue by rrfaria** [Lu-Yi-Hsun/iqoptionapi#204]
I talked with a brazilian group to start donate to you monthly to you continue with free version.

we need someone to contribute with open source version and videos on youtube or even live stream on twitch ... where you want...

and with long discution with some people they are open to contribute with donations to your project
to init is create a donation goal to develop features 
we are also open to contribute with issues and comments on git 
because you have helped us and now we wanna to give back 

thanks and we hope you enjoy this idea

**Comment by joaotolove** [comment]
this is a very good idea, because in addition to growing the API as a consolidated tool, we can contribute so that the author's work is valued !!  I currently believe that most users cannot pay for the paid version, for financial reasons, but, consensually, everyone is willing to contribute (with money) permanently to keep the API alive and growing!

**Comment by worloks** [comment]
Estou no mesmo grupo e gostariamos de fato de ajudar neste projeto, é um projeto que nos ajudou muito e gostariamos que continuasse a dar assistencia e prosseguir com este API.

Estamos dispostos a ajudar da melhor forma possivel, de forma financeira e também auxiliando no que precisar.

**Comment by worloks** [comment]
I am in the same group and we would really like to help in this project, it is a project that helped us a lot and we would like you to continue to assist and continue with this API.

We are willing to help in the best possible way, financially and also assisting in whatever you need.

**Comment by fera765** [comment]
Very good idea man .... To the developer we are willing to contribute

**Comment by DiMiTriFrog** [comment]
This is an amazing idea. I want to join in.

**Comment by allysonlm** [comment]
I think it's cool to continue the free project always a few versions before paying. Don't let the project die.

**Comment by webcomunik** [comment]
I agree and I can contribute with development and donation

**Comment by cardoso243** [comment]
Estou disposto a fazer doações mensais. 
Pra continuar com o projeto...

**Comment by Lu-Yi-Hsun** [comment]
ok

**Comment by Lu-Yi-Hsun** [comment]
ok i will open for free

**Comment by provezano** [comment]
what about developing your own version?

**Comment by Lu-Yi-Hsun** [comment]
@provezano I am not understand

**Comment by kkagill** [comment]
@Lu-Yi-Hsun he meant @rrfaria creates his own branch. 

So if you keep maintaining this repo, brazillian group plus repo users will start donating to you.

**Comment by provezano** [comment]
> @Lu-Yi-Hsun he meant @rrfaria creates his own branch.
> 
> So if you keep maintaining this repo, brazillian group plus repo users will start donating to you monthly.

Exactly!
