### ISSUE TITLE
Getting more than 1000 candles

### ISSUE THREAD

**Issue by ItamarRocha** [Lu-Yi-Hsun/iqoptionapi#205]
Hey guys. So, I'm trying to train a LSTM neural network with the data that I gathered from the API, but the problem is that The function get_candles() return only 1000 timesteps (candles). Does anyone has an updated database that is bigger than that or knows any way I can get more than that? I really appreciate.

**Comment by fera765** [comment]
start_candle = time.time()

for x in range(3):
  data=api.get_candles("EURUSD", 60, 1000, start_candle)
  start_candle=data[0]-1

**Comment by fera765** [comment]
`start_candle = time.time()

for x in range(3):
data=api.get_candles("EURUSD", 60, 1000, start_candle)
start_candle=data[0]-1`

**Comment by ItamarRocha** [comment]
> `start_candle = time.time()
> 
> for x in range(3):
> data=api.get_candles("EURUSD", 60, 1000, start_candle)
> start_candle=data[0]-1`
Buddy, thanks so much!
