### ISSUE TITLE
Multiple buy (call/put) not possible?

### ISSUE THREAD

**Issue by hcalitz** [Lu-Yi-Hsun/iqoptionapi#21]
Hi

My code runs through a loop, making decisions and call the call/put if needed.  It works for the first few times, but then reports the socket is closed.  The call/put goes through, it just seems the socket connection is lost. Can this be forced to stay open for multiple buy transactions?  

Part of my code(in a loop) is calling the transaction like this:
```
      trade_Amount = 1.2
      trade_ACTIVES = 'EURUSD'
      trade_ACTION= 'call'
      expirations_mode = 1
      force_buy = "True"
      trade_accepted, trade_id = IQ.buy(trade_Amount,
                                       trade_ACTIVES,
                                       trade_ACTION,
                                       expirations_mode,
                                       force_buy)

```                                
>  ERROR:root:**error** buy error...
> DEBUG:iqoptionapi.ws.client:Websocket connection closed.
> DEBUG:iqoptionapi.api:https://auth.iqoption.com/api/v1.0/login
> DEBUG:iqoptionapi.api:<Response [200]>
> DEBUG:iqoptionapi.api:{"data":{"ssid":"39550a949ca93cbbd672f58a0eaaaddc"}}
> DEBUG:iqoptionapi.api:{'Server': 'nginx', 'Date': 'Mon, 11 Jun 2018 17:27:33 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '52', 'Connection': 'keep-alive', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Accept, Accept-Language, Content-Type, YourOwnHeader', 'Access-Control-Allow-Methods': 'POST, GET, OPTIONS, PUT, DELETE', 'Access-Control-Allow-Origin': '*', 'Set-Cookie': 'ssid=39550a949ca93cbbd672f58a0eaaaddc; Path=/; Domain=iqoption.com; Max-Age=2592000', 'Strict-Transport-Security': 'max-age=15555600', 'X-Content-Type-Options': 'nosniff'}
> DEBUG:iqoptionapi.api:<RequestsCookieJar[<Cookie ssid=39550a949ca93cbbd672f58a0eaaaddc for .iqoption.com/>]>
> DEBUG:iqoptionapi.api:https://iqoption.com/api/getprofile
> DEBUG:iqoptionapi.api:<Response [200]>
> 
>  ERROR:root:**error** buy error...
> DEBUG:iqoptionapi.ws.client:Websocket connection closed.
> DEBUG:iqoptionapi.api:https://auth.iqoption.com/api/v1.0/login
> DEBUG:iqoptionapi.api:<Response [200]>
> DEBUG:iqoptionapi.api:{"data":{"ssid":"39550a949ca93cbbd672f58a0eaaaddc"}}
> DEBUG:iqoptionapi.api:{'Server': 'nginx', 'Date': 'Mon, 11 Jun 2018 17:27:33 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '52', 'Connection': 'keep-alive', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Accept, Accept-Language, Content-Type, YourOwnHeader', 'Access-Control-Allow-Methods': 'POST, GET, OPTIONS, PUT, DELETE', 'Access-Control-Allow-Origin': '*', 'Set-Cookie': 'ssid=39550a949ca93cbbd672f58a0eaaaddc; Path=/; Domain=iqoption.com; Max-Age=2592000', 'Strict-Transport-Security': 'max-age=15555600', 'X-Content-Type-Options': 'nosniff'}
> DEBUG:iqoptionapi.api:<RequestsCookieJar[<Cookie ssid=39550a949ca93cbbd672f58a0eaaaddc for .iqoption.com/>]>
> DEBUG:iqoptionapi.api:https://iqoption.com/api/getprofile
> DEBUG:iqoptionapi.api:<Response [200]>
>

**Comment by Lu-Yi-Hsun** [comment]
force_buy = "True" Will do for loop until  buy 

I think you false to buy 

You can pull last version try again

I will do more check tomorrow

**Comment by hcalitz** [comment]
A bit more information that may clarify my problem I am encountering ....
 
I played around with the parameters.  The "expirations_mode" seems to my problem. 

I am using this idea to stream candle data:
```
end_time = now + 60
while end_time > now :
    IQ.start_candles_stream("EURUSD") 
    candle_data =  IQ.get_realtime_candles("EURUSD"))
    ...
    IQ.buy(trade_Amount,  trade_ACTIVES, trade_ACTION,  expirations_mode,  force_buy)
   ... 
   
I_want_money.stop_candles_stream("EURUSD")
```
utilising a timer to stream for an hour or more. The socket closes after the "expirations_mode" setting is reached.  My code wants to stream candle data and make another "IQ.buy" after the "expirations_mode" time limit is reached.

**Comment by Lu-Yi-Hsun** [comment]
you can use 
(in README)
```
id=23243221#this id is buy's id ,you can get it from buy function
I_want_money.check_win(id)
```
it will do loop until your bet have answer

**Comment by hcalitz** [comment]
Thank you ... I traced the problem to two things ... a space in a "call "  string and I needed to make the buy call before the time expired.  You pointed me in the right direction.   Thanks!
