### ISSUE TITLE
Buy returning same ID on threaded buy

### ISSUE THREAD

**Issue by geraldogebler** [Lu-Yi-Hsun/iqoptionapi#215]
If I buy 2 turbo actives at the same second (using thread), the buy method are returning the same ID on both threads, instead returning the ID of each buy.

I use the ID to check win or loss, so, I cant give up this information....
![image](https://user-images.githubusercontent.com/64275214/80266556-d4096280-8672-11ea-80a1-2b4f5915030d.png)
![image](https://user-images.githubusercontent.com/64275214/80268910-b7c0f200-8681-11ea-9a1c-294951c69be7.png)
![image](https://user-images.githubusercontent.com/64275214/80268935-d4f5c080-8681-11ea-8e21-7609e76c6f43.png)

Tried using mult too... but the result is the same... the variable "data_sinal" is a datetime with my entry signal.

**Comment by landimd** [comment]
I think that this API is not thread safe. I tried before and got wrong values. take a look at this issue.

**Comment by geraldogebler** [comment]
This would be so sad... My entire cod is thread based to work on signals list, which could be various at the same time (including martingale strategies)... Tried using mult processing, as the API creator told in this link, but an freeze error appears... Let's see if someone has some answer

**Comment by geraldogebler** [comment]
> I think this API is not thread safe. I tried before and got wrong values. take a look at this issue #150. I'm not sure if it was fixed.

Buddy, did you find out a way to buy turbo using threads and got succeed?

**Comment by geraldogebler** [comment]
A few tests later... Turns out the buy_digital_spot method are returning the same ID too when using threads and buying on same second... @Lu-Yi-Hsun

**Comment by provezano** [comment]
You'd probably need to change the api source code to make the buy function thread safe. The author of this api much probably won't help you with it.

**Comment by geraldogebler** [comment]
> You'd probably need to change the api source code to make the buy function thread safe. The author of this api much probably won't help you with it.

Yes, I did it and solve the problem to the buy method. Working on buy_digital_spot which has the same issue.

**Comment by provezano** [comment]
If you feel like contributing, you could publish your solution. There are other people facing the same issue.

**Comment by Lu-Yi-Hsun** [comment]
Thread safe is doing

**Comment by provezano** [comment]
> Thread safe is doing

What do you mean?

**Comment by Lu-Yi-Hsun** [comment]
Implement in private

**Comment by geraldogebler** [comment]
Buy_digital_spot is fixed too?

**Comment by Lu-Yi-Hsun** [comment]
Not yet , tomorrow I am keep doing .

For now only support buy buy_multi

**Comment by geraldogebler** [comment]
Solved both buy and buy_digital_spot on my own.

**Comment by danielWagnerr** [comment]
Can you contribute with us how did you solve this problem?

**Comment by wallacemv** [comment]
> Solved both buy and buy_digital_spot on my own.

how?!

**Comment by hugoramos** [comment]
up

**Comment by emilioPonceAlvarado16** [comment]
I'm facing the same issues, is this already fixed?, I am using a try except block to handle the errors and re-try, but doesn't work everytime there are too many operations with the same ACTIVE, created_time. Need some help
