### ISSUE TITLE
get_digital_spot_profit_after_sale SOLVED

### ISSUE THREAD

**Issue by KGTeixeira** [Lu-Yi-Hsun/iqoptionapi#227]
if you have an error like this:

 line 990, in get_digital_spot_profit_after_sale
    ACTIVES = position['instrument_underlying']
KeyError: 'instrument_underlying'

go to file stable_api.py in the line indicated above and switch to this:

ACTIVES = position['raw_event']['instrument_underlying']

**Comment by mdandidarmawan** [comment]
Is it already committed?
