### ISSUE TITLE
Buy at the same time on different threads

### ISSUE THREAD

**Issue by danielWagnerr** [Lu-Yi-Hsun/iqoptionapi#229]
I'm trying to buy on different threads and different accounts at the same time, but the thread that runs the first one can buy and the second one can't. Does anyone have any idea how to get around this problem?

**Comment by provezano** [comment]
As you are using different accounts you can use multiprocessing and treat each buy order as a new process

**Comment by danielWagnerr** [comment]
Thanks for the suggestion, it worked perfectly.
