### ISSUE TITLE
ERROR:root:buy_digital_spot active error

### ISSUE THREAD

**Issue by JuanRcl** [Lu-Yi-Hsun/iqoptionapi#232]
I try to execute the order in digital format, but it shows this error. When I execute the buy function in binary, it does not return any error.
I need help to find out what the problem is, all I need is the option to buy on digital and my bot will be ready.
below is the code.

active = "EURUSD"
amount = 2
action = "PUT"
duration = 1

Iq.buy_digital_spot(active,amount, action, duration)

**Comment by provezano** [comment]
Action should be **put** or **call**, in lowercase.
PUT, in uppercase, is not a valid action.

**Comment by JuanRcl** [comment]
It worked, thank you very much!
