### ISSUE TITLE
API not work with real account?

### ISSUE THREAD

**Issue by jariojose** [Lu-Yi-Hsun/iqoptionapi#233]
Firstly, congratulations on this work! It is amazing!

If I use: API.change_balance('PRACTICE')
And then: API.buy_digital_spot('EURUSD', 1, 'pull', timeframe)

It works!

But, If I use: API.change_balance('REAL')
And then: API.buy_digital_spot('EURUSD', 1, 'pull', timeframe)

Not happens.

What is my noob action? Lol

Thank you!

**Comment by provezano** [comment]
Is your account in R$ or $?
If it is a R$ account, you cannot make R$ 1.00 trades.
Also, pull is not a valid action. Only put and call.

**Comment by jariojose** [comment]
Thank you, dear!
