### ISSUE TITLE
get_live_deal - Is possible to check if the a specific user_id / order_id win or loss?

### ISSUE THREAD

**Issue by jariojose** [Lu-Yi-Hsun/iqoptionapi#235]
Is there some function to check if a live_deal has won or lost?

For example: trades = API.get_live_deal(type, name, timeframe)

Is possible to check the process?

**Comment by mdandidarmawan** [comment]
Can it be?

**Comment by jariojose** [comment]
So, I implemented it... But, there is a lot of problem about this. The first is the delay. When a user makes an order, you must monitor to check when the order_time finishes, the order was successfully or no.

I intend to use a neural network to train with it. But, I need a lot of additional info: news, candle pattern, candle stats....
