### ISSUE TITLE
CONNECTION ERROR

### ISSUE THREAD

**Issue by jesielcarlos** [Lu-Yi-Hsun/iqoptionapi#236]
The connect () function is returning this error to me:
(False, '[Errno 11004] getaddrinfo failed')

**Comment by RafaelDamiani** [comment]
Paste a part of your code here, then we can help you. With only this message is not possible understand what's happening.

**Comment by jesielcarlos** [comment]
> Cole uma parte do seu código aqui, para que possamos ajudá-lo. Com apenas esta mensagem não é possível entender o que está acontecendo.

Já resolvi, obrigado!
