### ISSUE TITLE
Copy of account DEMO or REAL?

### ISSUE THREAD

**Issue by ElLuigi** [Lu-Yi-Hsun/iqoptionapi#241]
How can I find out if the account being copied is operating on a demo or real account?

I am using this get "API.get_user_profile_client(idTrader)", but it always shows "is_demo_account": false,

API.get_user_profile_client(IdTrader)
logging.info(json.dumps(operador, indent=1))

{
 "balances": [],
 "client_category_id": 1,
 "country_id": 42,
 "flag": "CL",
 **"is_demo_account": false,**
 "is_vip": false,
 "vip_badge": false,
 "isSuccessful": true,
 "registration_time": 1556128147,
 "selected_asset_id": -1,
 "selected_balance_type": -1,
 "selected_option_type": -1,
 "user_id": 45583687,
 "user_name": "Giezi josue Martinez",
 "status": "online",
 "gender": "1"
}
This data will be correct? never shows "is_demo_account": true,

**Comment by GaboLeguiza** [comment]
For me this Api does not differ from which account it takes the operations, it takes from the demo and real accounts of the top.
I have no evidence but neither do I doubt.
