### ISSUE TITLE
Trading on forex market

### ISSUE THREAD

**Issue by tejado** [Lu-Yi-Hsun/iqoptionapi#27]
Hey,

as far as I can see, the API doesn't include the possibility to trade on the forex market but only options.
Is there a special reason why the API calls for trading forex are not implemented (yet)? Otherwise I would like to support the implementation!

Cheers!

**Comment by Lu-Yi-Hsun** [comment]
@tejado 
yes i will add forex api today

**Comment by tejado** [comment]
Awesome! If you need some help/support (e.g. you can create issues with the label "help wanted"), tell me :)

**Comment by Lu-Yi-Hsun** [comment]
@tejado 

i have been update last version you can try

**Comment by tejado** [comment]
Thank you!
