### ISSUE TITLE
Candle streams function demand extra argument

### ISSUE THREAD

**Issue by keithomayot** [Lu-Yi-Hsun/iqoptionapi#279]
Hi ,
just encountered a problem when using the following functions. It an extra argument not shown in the documentation. The function with the extra arguments are below("self:IQOption"):
IQOption.start_candles_stream(self: IQOption, ACTIVE, size, maxdict)
IQOption.stop_candles_stream(self: IQOption, ACTIVE, size)
IQOption.get_realtime_candles(self: IQOption, ACTIVE, size) 

adding IQOption as first argument when calling them brings the following error:
File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pyiqoptionapi\iqoption.py", line 799, in start_candles_stream
    elif size in self.size:
TypeError: argument of type 'property' is not iterable

How do we sought this Out?

**Comment by andredezzy** [comment]
You can use by default 20, this value is used on examples into the documentation.

**Comment by Kinjeketile-Ngwai** [comment]
Works like a charm, thank you very much
