### ISSUE TITLE
dictionary keys changed during iteration

### ISSUE THREAD

**Issue by jhonrey1010** [Lu-Yi-Hsun/iqoptionapi#284]
Error appears when running the Talib.RSI using live candle data for a short period time (e.g. 5 min, or less)

```
Iq.start_candles_stream("EURUSD",60,300)
while True:
    candles=Iq.get_realtime_candles("EURUSD",60)
    inputs = {
        'open': np.array([]),
        'high': np.array([]),
        'low': np.array([]),
        'close': np.array([]),
        'volume': np.array([])
    }
    for timestamp in candles:
        inputs["open"]=np.append(inputs["open"],candles[timestamp]["open"] )
        inputs["high"]=np.append(inputs["open"],candles[timestamp]["max"] )
        inputs["low"]=np.append(inputs["open"],candles[timestamp]["min"] )
        inputs["close"]=np.append(inputs["open"],candles[timestamp]["close"] )
        inputs["volume"]=np.append(inputs["open"],candles[timestamp]["volume"] )
    print(RSI(inputs, timeperiod=2)[-2])
    time.sleep(0.5)
    
    

  Traceback (most recent call last):
  File "C:\blah\blah\iqoptionapi-master\test.py", line 27, in <module>
    for timestamp in candles:
RuntimeError: dictionary keys changed during iteration
```

**Comment by estdysogoods** [comment]
for timestamp in list(candles.keys()):

https://youtu.be/7qBlySS98C8

**Comment by estdysogoods** [comment]
try:
  for timestamp in list(candles.keys()):
          inputs["open"]=np.append(inputs["open"],candles[timestamp]["open"] )
          inputs["high"]=np.append(inputs["open"],candles[timestamp]["max"] )
          inputs["low"]=np.append(inputs["open"],candles[timestamp]["min"] )
          inputs["close"]=np.append(inputs["open"],candles[timestamp]["close"] )
          inputs["volume"]=np.append(inputs["open"],candles[timestamp]["volume"] )
except:
    pass #or print("error")
