### ISSUE TITLE
Bollinger Bands Strategy

### ISSUE THREAD

**Issue by provezano** [Lu-Yi-Hsun/iqoptionapi#296]
I coded a fully automatic and real-time bot to trade Berman's Strategy (https://youtu.be/mQXcRDBoNi0) that uses Bollinger Bands and EMA's to make trading decisions. Hope it can be helpful to anyone wanting to construct its own bot with real-time strategy.

See it here: https://github.com/provezano/IQBBot

**Comment by octaviodegodoy** [comment]
I´m adding new features to the code, please let me know if you already tried using martin or sorosgale

**Comment by TheHolsback** [comment]
I have the code for martin and Soros and already runned a few days, but I warning u guys, it's not what u thinking. It's not good this strategy
