### ISSUE TITLE
Unable to import 'iqoptionapi.stable_api'

### ISSUE THREAD

**Issue by ToMattBan** [Lu-Yi-Hsun/iqoptionapi#299]
Hey.

I've runned this: 'pip install -U git+git://github.com/iqoptionapi/iqoptionapi.git', then I created a 'main.py' file and tried to run the sample code, but when I do this, I get a error who say "ModuleNotFoundError: No module named 'iqoptionapi' "

What I'm doing wrong?

**Comment by ToMattBan** [comment]
I've installed now with 

`sudo pip install -U git+git://github.com/iqoptionapi/iqoptionapi.git`

And now work

**Comment by snaab64** [comment]
yes!..using : pip install -U git+git://github.com/iqoptionapi/iqoptionapi.git  at cmd line of Windows 11...  it's working!!
