### ISSUE TITLE
buy_digital_spot is always getting only 60% of profit

### ISSUE THREAD

**Issue by blackdemonchess** [Lu-Yi-Hsun/iqoptionapi#307]
Dear all,
Since 9 June 2021, when I use the function **buy_digital_spot(ACTIVES,amount,action,duration)**, if I win I get always 60% of profit, instead of the profit showed in the IQoption web site (ex: 95%)

This is the code

ACTIVES="EURUSD"
duration=1
amount=1
action="put"
iq.buy_digital_spot(ACTIVES,amount,action,duration)

Some one has any idea?
Thanks

**Comment by blackdemonchess** [comment]
I found the solution, I need to use the version V2 of the function:

iq.buy_digital_spot_v2(ACTIVES,amount,action,duration)

**Comment by Yutheforce** [comment]
Hello, how do you check digital profit after sale using buy_digital_spot_v2 
this one: get_digital_spot_profit_after_sale(id) does not work
