### ISSUE TITLE
get remaining time

### ISSUE THREAD

**Issue by dzmodest** [Lu-Yi-Hsun/iqoptionapi#32]
Hi,
how to get the remaining time in seconds of an asset?
https://iqoptionapi.readthedocs.io/en/latest/iqoptionapi.ws.objects.html#module-iqoptionapi.ws.objects.timesync
https://github.com/Lu-Yi-Hsun/iqoptionapi/blob/master/iqoptionapi/ws/objects/timesync.py

TimeSync have that options defined already, but how to access it from the main api (iqoptionapi.stable_api.IQ_Option)

edit: I'm not sure that that expiration_datetime reffers to the asset remaining purchase time, but worth to include it.

**Comment by Lu-Yi-Hsun** [comment]
input expiration 

sample if you buy in 60sec(1 min) 
input get_expiration_time(1) and you can get purchase time
```python
def get_expiration_time(t):
    exp=time.time()
    if (exp % 60) > 30:
        end = exp - (exp % 60) + 60*(t+1)
    else:
        end = exp - (exp % 60)+60*(t)
    return end-30-exp
```

**Comment by dzmodest** [comment]
@Lu-Yi-Hsun 
that's not what i meant
this is just a count down to a time i choose

what i mean is to get the left purchase time from iq option, see picture:
![iqoption_leftpurchasetime](https://user-images.githubusercontent.com/16493223/44629457-8ab9ba80-a947-11e8-9519-2a73929f9d95.png)

**Comment by Lu-Yi-Hsun** [comment]
@dzmodest 
yes it is" purchase time" 
 you can try that code

**Comment by dzmodest** [comment]
@Lu-Yi-Hsun 
it just look that have no relation with the iq option api
i have tried the code, not giving the same time as in iqoption

**Comment by dzmodest** [comment]
@Lu-Yi-Hsun
i understand you are trying to use the same code that iqoption use
in fact the result are close (10sec delay)
iqoption: 10sec
code: 20sec

the question is does iqoption calculate the purchase time that way (minus 10sec) in all the cases or it depends?

**Comment by Lu-Yi-Hsun** [comment]
try this
```python
import time
def get_expiration_time(t):
    exp=time.time()
    if (exp % 60) > 30:
        end = exp - (exp % 60) + 60*(t+1)
    else:
        end = exp - (exp % 60)+60*(t)
    return end
end_time=0
while True:
    if end_time-30-time.time()<=0:
        end_time = get_expiration_time(2)
    print(end_time-30-time.time())
    time.sleep(1)

```

**Comment by Lu-Yi-Hsun** [comment]
can not get iqoption "purchase time" by network.

**Comment by dzmodest** [comment]
@Lu-Yi-Hsun 
the first codes works better (still diff 10sec)
the second code output something completely different

it's okay, for now i will use the first code and takeoff the 10sec as long as it's that way

in case you get a better code, update the readme file

closing this case for now.
thanks for following up.
