### ISSUE TITLE
Can it be used to get interactive binary trade?

### ISSUE THREAD

**Issue by JafferWilson** [Lu-Yi-Hsun/iqoptionapi#38]
Hello @Lu-Yi-Hsun ,
I was going through the API, found it fascinating. I have seen that you have build the API on top of other repository. I have check it too. You repository is more simple to understand then his. 
Well, I have a question regarding your api. You see this software or bot: https://github.com/n1nj4z33/iq-bot is created by the same person and it give live and interactive automated trading experience and also connect with MT.
I wanted to know whether your API can give the same trading experience, or is just a connection? Please let me know if you have any such bot build on top of your API.

Or
Is it possible that I can see my applied bet on the screen or something please? That will help me a lot.

**Comment by Lu-Yi-Hsun** [comment]
@JafferWilson 
https://github.com/n1nj4z33/iq-bot this robot is fundamental on chrome by using selenium package

In the first time ,I was writing a robot on chrome(like iq-bot) and you can view the action,but that have a very big problem!!
The robot is not stable!! 
Because the robot is fundamental on chrome so  it often "lag" or "crash"!!!
so I think this api is the best way to write a robot for run long time

**Comment by JafferWilson** [comment]
@Lu-Yi-Hsun  I can understand what crashing issues you might have faced. But the newest update of Chrome is quite different and it might work properly. Well, leave it. But can it be possible via your api to know where the bid was placed? Can you add a GUI so it will be visible so that it will help in understand that everything works fine. Please can you help with that too?

**Comment by Lu-Yi-Hsun** [comment]
can not get order book (bid/ask) and volume data , iqoption not share that data
you mean gui view realtime candle? you can try matplotlib

**Comment by JafferWilson** [comment]
@Lu-Yi-Hsun Is there no way I can visualize the Websocket that the API uses?

**Comment by Lu-Yi-Hsun** [comment]
@JafferWilson
You can turn on the debug mode ,and you can view the websocket

**Comment by JafferWilson** [comment]
Thank you, @Lu-Yi-Hsun . Please guide me to turn the debug mode On. How I can do that. Do let me know.

**Comment by Lu-Yi-Hsun** [comment]
I was writing done on the document
```python 
import logging
logging.basicConfig(level=logging.DEBUG,format='%(asctime)s %(message)s')
```

**Comment by JafferWilson** [comment]
> I was writing done on the document
> 
> ```python
> import logging
> logging.basicConfig(level=logging.DEBUG,format='%(asctime)s %(message)s')
> ```

Thank you @Lu-Yi-Hsun but this shows set of lines on the command line. I was willing to see it visually. That was the reason of me raising the issue here.

**Comment by Lu-Yi-Hsun** [comment]
If you want full visually robot .. i think https://github.com/n1nj4z33/iq-bot
Is the easy way. Is that robot working well?
Iqoption is output image not html so that need opencv..

**Comment by JafferWilson** [comment]
Yes, I am getting some issues while dealing with it. I can share my script with you if you can help with it then it will be awesome. I tried to modify the script of the bot but it is only working till the tradesroom and no further as I am stuck with the image that IQO is making available.

**Comment by Lu-Yi-Hsun** [comment]
@JafferWilson 
you can try OPENCV to do that ,catch the window screen and Identification where the button.
or you can write the const location 

(i was done that before but that robot is very slow even crash because using OPENCV and chrome and selenium)

**Comment by JafferWilson** [comment]
@Lu-Yi-Hsun  So there must be something else I guess apart from Opencv. Need to try it out. May be Selenium itself will help. what you think?

**Comment by JafferWilson** [comment]
@Lu-Yi-Hsun  I am closing this thread, as I guess there isn't any solution for it, that might help in seeing the bets. Thank you Lu for your help and guidance.

**Comment by incafox** [comment]
maybe pyautogui + pre-mapped locations?

**Comment by incafox** [comment]
thet n1nj4z33's bot project is not the best way to make a bot, as  Lu-Yi-Hsun said, a nice option is get all the data from Lu-Yi-Hsun's api and make it visually easier with some package like bokeh or plotly, (i'm using bokeh right now), so you can draw anything that you want, things like automatized strategies, critical points ... etc, but i'm not sure how good is make this on binary option "market" (as every proff trader say)
