### ISSUE TITLE
Getting only 1000 candles.

### ISSUE THREAD

**Issue by JafferWilson** [Lu-Yi-Hsun/iqoptionapi#39]
I have tried the following way to collect the dataset, but got only 1000 candles and no more.
```
>>> data = pd.DataFrame(I_want_money.get_candles(goal,60,70000, time.time()))
>>> data["at"] = pd.to_datetime(data["at"], format ='%Y.%m.%d %H:%M')
>>> data.to_csv("candles.csv",index=False)
```
Please help me.

**Comment by Lu-Yi-Hsun** [comment]
@JafferWilson  yes! iqoption only can get 1000 candle once time!!
so you need to write a for loop to get more!

**Comment by JafferWilson** [comment]
@Lu-Yi-Hsun Is there no way to get the candles more than 1000? I hope there must be something in the code that can be done. Please help me.

**Comment by Lu-Yi-Hsun** [comment]
@JafferWilson 
```python
from iqoptionapi.stable_api import IQ_Option
import time
I_want_money=IQ_Option("email","password")
end_from_time=time.time()
ANS=[]
for i in range(2):
    data=I_want_money.get_candles("EURUSD", 60, 2, end_from_time)
    ANS =data+ANS
    end_from_time=int(data[0]["from"])-1
print(ANS)

```

**Comment by JafferWilson** [comment]
Thank you @Lu-Yi-Hsun. I tried this. But the candles that I got is something like this:  
![testiqoption candles](https://user-images.githubusercontent.com/13446197/46931979-3390b600-d06b-11e8-967f-09d2b4cb3e39.png)
I see that the candles returned are not like the actual candles that are on the IQO. Please can you check it once? I see OHLC values but no biid ask values .. may thats the reason for the weird candles.

**Comment by Lu-Yi-Hsun** [comment]
@JafferWilson
How to print candle to that image?
Iqoption do not sent ask/bid .
Only OHLC

**Comment by JafferWilson** [comment]
Basically I am using MT5 - Metatrader5 to visualize the candles that are sent through your api.
Hence, I am a bit concerned why is this happening? The MT5 show only what it receives. ultimatey it just a visualization point for the candles.

**Comment by Lu-Yi-Hsun** [comment]
@JafferWilson 
what time you catch

give me your raw data (csv file)

**Comment by JafferWilson** [comment]
Ok @Lu-Yi-Hsun I will share the data file with you, here it is: 

[10001candles.txt](https://github.com/Lu-Yi-Hsun/iqoptionapi/files/2478364/10001candles.txt)
Please let me know, if there is any issue.

**Comment by Lu-Yi-Hsun** [comment]
@JafferWilson 
1970-01-01?
you get the data from iqoption?
iqoption do not have volume

**Comment by JafferWilson** [comment]
Ok check this new file then:  
[10001candles.txt](https://github.com/Lu-Yi-Hsun/iqoptionapi/files/2478585/10001candles.txt)
Please check this.. Still I am having trouble plotting. Please can you
 check it once.

**Comment by Lu-Yi-Hsun** [comment]
@JafferWilson 
try this code output iqoption candle to csv for MT5
i have been check it is same as iqoption plot
1.check MT5 Timeframes is right
2.if you view large gap of candle (1).check your data do not miss (2) or the data is cross to holiday
```python
from iqoptionapi.stable_api import IQ_Option
import time
import datetime
I_want_money=IQ_Option("yihsun1992@gmail.com","movrax,4int0x80")
end_from_time=time.time()
ANS=[]
for i in range(1):
    data=I_want_money.get_candles("EURUSD", 60, 1000, end_from_time)
    ANS =data+ANS
    end_from_time=int(data[0]["from"])-1
ok=""
for li in ANS:
    value = datetime.datetime.fromtimestamp(li["to"])
    exct_time =value.strftime('%Y.%m.%d %H:%M:%S')
    ok=exct_time+","+str(li["open"])+","+str(li["max"])+","+str(li["min"])+","+str(li["close"])+","+str(li["volume"])+"\n"+ok
fp=open("MT5.csv","w+")
fp.write(ok)
```

**Comment by JafferWilson** [comment]
@Lu-Yi-Hsun  Have a look at the two images. 
This one is from the IQoption:   
![real](https://user-images.githubusercontent.com/13446197/46994635-e4ae5380-d132-11e8-9905-d378fdf17610.PNG)

The following is from the MT5: 
![got](https://user-images.githubusercontent.com/13446197/46994646-ee37bb80-d132-11e8-9337-7da9bf2b5f91.PNG)

Kindly, let me know whether they look same to you. Please let me know what might have caused this issue.

**Comment by Lu-Yi-Hsun** [comment]
@JafferWilson  give me timestamp so we can talk the same range!
you check the value is different?

**Comment by JafferWilson** [comment]
Hey @Lu-Yi-Hsun can you share the code that you used in MT5 for it? I am trying to make it but getting different result still may be  made some another mistake in displaying the stuff.

**Comment by Lu-Yi-Hsun** [comment]
@JafferWilson 
you mean MT5 call this api function to general the candle?
i do not know MT5 code! 
i general the data from this api,and import the data to MT5

**Comment by JafferWilson** [comment]
@Lu-Yi-Hsun  While importing it uses json and not the csv, right? and with your code your are creating a csv file not json? how you have import data using csv. I am not understanding how you get so much clear data, I am amazed to see.

**Comment by Lu-Yi-Hsun** [comment]
@JafferWilson 
no! it need to import .csv/.prn/.txt
View->Symbols->Create Custom  Symbol->click your new Symbol->Bars->import Bars->Browse
and you can import the data

**Comment by JafferWilson** [comment]
Yes yes.. I got it .. I forgot almost.. I am trying it out.. thank you.. I am checking if it works for me.

**Comment by JafferWilson** [comment]
Dear @Lu-Yi-Hsun  Please have a look at this image: I do not understand what might be the issue. I tried everything but still the candles are the same way they looked before. Have a look at the image:  
![testiqo](https://user-images.githubusercontent.com/13446197/47005123-bc355200-d150-11e8-904f-dc64888cd26e.png)

There is a lot of dojis. Please let me know whether this is a fault of IQO api or is there anything you think is there any mistake in my way? I tried it your way this time by importing but the same thing happened.

**Comment by Lu-Yi-Hsun** [comment]
what your timestamp?

**Comment by JafferWilson** [comment]
Here have a look at the file:  
[MT5.txt](https://github.com/Lu-Yi-Hsun/iqoptionapi/files/2482280/MT5.txt)
Try using this. I have changed one line from your current where you have mentioned end time:
`end_from_time=1539675885`
to
`end_from_time=time.time()`
As I was in need of candles from current time.

**Comment by Lu-Yi-Hsun** [comment]
check the value is same or different?

**Comment by JafferWilson** [comment]
See the following @Lu-Yi-Hsun : 
![test](https://user-images.githubusercontent.com/13446197/47006893-9dd15580-d154-11e8-903b-e5855f90fd67.png)
Have a look at this. This values are getting truncated I guess.

**Comment by JafferWilson** [comment]
You helped a lot my friend I guess this is the fault of MT5 itself. I will check with them.

**Comment by JafferWilson** [comment]
Thank you very much for your help ... :)

**Comment by Lu-Yi-Hsun** [comment]
@JafferWilson 
my pleasure
