### ISSUE TITLE
start_candles_stream   

### ISSUE THREAD

**Issue by remarco** [Lu-Yi-Hsun/iqoptionapi#4]
how to parse this dict in usable candles?
i dont understand how to dict is work? how can i get 
______________ from________ min_______max_____close____ open
candle[1] [1524731626, 1.21747, 1.21748, 1.21747, 1.21748]
candle[2] [1524731626, 1.21747, 1.21748, 1.21747, 1.21748]
candle[3] [1524731626, 1.21747, 1.21748, 1.21747, 1.21748]

and now i can work like  candle[1][1] > candle[1][4] 
or candle[1][1] + candle[1][4] = sum/2
or something like that.

if i tray 
a = (I_want_money.thread_collect_realtime)
----------a is dict
b=a.values()
----------then b is list
c=b[0]
--------- c is dict

**Comment by remarco** [comment]
````
a= (I_want_money.thread_collect_realtime)

print "+++++Keys : ",a.keys()
print "-----values : ",a.values()
print "=====items : ",a.items()

+++++Keys :  [1524733184434973042L, 1524733184457356148L]
-----values :  [{u'from': 1524733184, u'min': 1.21725, u'max': 1.21725, u'bid': 1.217105, u'volume': 0, u'to': 1524733185, u'at': 1524733184434973042L, u'ask': 1.217395, u'close': 1.21725, u'active_id': 1, u'open': 1.21725, u'id': 10948803, u'size': 1}, {u'from': 1524733184, u'min': 1.21725, u'max': 1.21725, u'bid': 1.217105, u'volume': 0, u'to': 1524733185, u'at': 1524733184457356148L, u'ask': 1.217395, u'close': 1.21725, u'active_id': 1, u'open': 1.21725, u'id': 10948803, u'size': 1}]
=====items :  [(1524733184434973042L, {u'from': 1524733184, u'min': 1.21725, u'max': 1.21725, u'bid': 1.217105, u'volume': 0, u'to': 1524733185, u'at': 1524733184434973042L, u'ask': 1.217395, u'close': 1.21725, u'active_id': 1, u'open': 1.21725, u'id': 10948803, u'size': 1}), (1524733184457356148L, {u'from': 1524733184, u'min': 1.21725, u'max': 1.21725, u'bid': 1.217105, u'volume': 0, u'to': 1524733185, u'at': 1524733184457356148L, u'ask': 1.217395, u'close': 1.21725, u'active_id': 1, u'open': 1.21725, u'id': 10948803, u'size': 1})]

**Comment by Lu-Yi-Hsun** [comment]
@remarco
What value ? I am not understand .

**Comment by remarco** [comment]
Look second post. Values from dict. I not understan hov tu get one value. I can get all values not one. An then it not dic but change to list ....

**Comment by Lu-Yi-Hsun** [comment]
@remarco
https://stackoverflow.com/questions/26660654/how-do-i-print-the-key-value-pairs-of-a-dictionary-in-python

**Comment by remarco** [comment]
Loot to second post. Wee have key an value. In value wee have also key and value

**Comment by remarco** [comment]
Look to second post. Wee have key an value. In value wee have also key and value
