### ISSUE TITLE
Information on candle data

### ISSUE THREAD

**Issue by ildeb** [Lu-Yi-Hsun/iqoptionapi#40]
@Lu-Yi-Hsun

I did not understand the meaning of some candle data fields:

{'id': 160345,
  'from': 1522886640,
  'at': 1522886700047986247,
  'to': 1522886700,
  'open': 1.228845,
  'close': 1.228875,
  'min': 1.228835,
  'max': 1.228875,
  'volume': 0},
 
Is the "at" row a timestamp expressed in nanoseconds? What exactly is it for?
What about the "from" and "to" rows?

Thank you very much!

**Comment by Lu-Yi-Hsun** [comment]
@ildeb 
timestamp 
from:1522886640~at: 1522886700047986247~to:1522886700
