### ISSUE TITLE
Not getting the volume for all the historic data.

### ISSUE THREAD

**Issue by JafferWilson** [Lu-Yi-Hsun/iqoptionapi#41]
@Lu-Yi-Hsun I am trying to fetch the historic data through your api. When I plotted them I came to see that there are volumes missing. Please let me know why I have the volumes for limited period and not all. 
See the image:  
![picturemessage_cnk51s1l yjg](https://user-images.githubusercontent.com/13446197/47295126-94e8f400-d62c-11e8-9be8-ebc279c178ef.png)

**Comment by Lu-Yi-Hsun** [comment]
I can not find where is missing

**Comment by JafferWilson** [comment]
Sure @Lu-Yi-Hsun , I will share data with you. Here is the example:
![missing](https://user-images.githubusercontent.com/13446197/47336275-abcf2b00-d6ac-11e8-93af-63d73281300b.PNG)
The data is attached here:  
[MT5.zip](https://github.com/Lu-Yi-Hsun/iqoptionapi/files/2504543/MT5.zip)
Please let me know.

**Comment by Lu-Yi-Hsun** [comment]
i do not know why.

you can print log to find what happen in there

**Comment by JafferWilson** [comment]
I am worried as the log may be too long to understand. I tried another methods like checking the values  on IQO. I didn't find the entries there too. I don't know why is this happening. @Lu-Yi-Hsun Can you once check it?

**Comment by Lu-Yi-Hsun** [comment]
So you can not get that time data?

**Comment by JafferWilson** [comment]
That means my analysis will remain stuck up..... Is there nothing you can do?

**Comment by JafferWilson** [comment]
@Lu-Yi-Hsun Is there a way I can connect the real time candles in the MT5 using your API? Do your API returns the exact values? I have seen many a times there is a difference of 0.00005. May be more or less. But the difference is persistent which is not good. This happens when I tried to fetch the 60 seconds candle using your api.
Please let me know.

**Comment by Lu-Yi-Hsun** [comment]
you use realtime candle or get candle?

**Comment by Lu-Yi-Hsun** [comment]
Yes realtime candle need to mix with getcandle function to fix that

**Comment by JafferWilson** [comment]
Ok Thank you @Lu-Yi-Hsun. I think there is some problem with the IQO not with the API. Thank you for your assistance.

**Comment by Lu-Yi-Hsun** [comment]
@JafferWilson  that my api problem! i will fix that QQ

**Comment by JafferWilson** [comment]
@Lu-Yi-Hsun Thank you. If it works then it will be awesome.
