### ISSUE TITLE
get_poisition_history

### ISSUE THREAD

**Issue by elmschaym** [Lu-Yi-Hsun/iqoptionapi#43]
anyone can help me i to get the position history in binary option or maybe all the instrument_type thanks and advance

**Comment by Lu-Yi-Hsun** [comment]
get_position_history?

i have been write sample on the api

**Comment by elmschaym** [comment]
thanks for your sample, but there is no sample for Binary Option only forex, cfd and crypto., in param instrument_type what type i use to get the position history of binary

**Comment by Lu-Yi-Hsun** [comment]
Try get_betinfo

**Comment by elmschaym** [comment]
> get_betinfo

ok thanks, the position history and the trading history are the same?
