### ISSUE TITLE
Close half position

### ISSUE THREAD

**Issue by ildeb** [Lu-Yi-Hsun/iqoptionapi#45]
@Lu-Yi-Hsun
is it possible to partially close a position?

**Comment by Lu-Yi-Hsun** [comment]
i do not understand

**Comment by JafferWilson** [comment]
@ildeb  What is this partially close position? Can you share a snapshot of what are you trying to say?

**Comment by incafox** [comment]
![selli](https://user-images.githubusercontent.com/4401153/47957833-6a335f80-df8b-11e8-9594-975a006a28bc.png)

**Comment by Lu-Yi-Hsun** [comment]
For binary option?
Ok I add that function for binary option today

**Comment by Lu-Yi-Hsun** [comment]
@incafox 
please update to last version!

**Comment by incafox** [comment]
Thanks ¡¡ :)

**Comment by ildeb** [comment]
> @incafox
> For binary option?
> Ok I add that function for binary option today

@Lu-Yi-Hsun
could you add this function for forex market?

**Comment by Lu-Yi-Hsun** [comment]
@ildeb  please read document , cancel_order,close_position
