### ISSUE TITLE
get_position_history not working

### ISSUE THREAD

**Issue by JafferWilson** [Lu-Yi-Hsun/iqoptionapi#46]
Hello @Lu-Yi-Hsun ,
I have tried to capture the trade history using the api. But I received this:
```
>>> I_want_money.get_positions_history("forex")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'IQ_Option' object has no attribute 'get_positions_history'
```
I am using Python 3.5, Windows 10 Home Edition. and the latest version of your api. 
```
>>> IQ_Option.__version__
'2.1.3'
```
Please let me know what is the problem.
Also I would like to know how I can access the bet position/price of the binary? Where exactly my bet is placed?

**Comment by Lu-Yi-Hsun** [comment]
thank i fix that in README.MD
is "get_position_history"
not "get_positions_history"

**Comment by JafferWilson** [comment]
@Lu-Yi-Hsun  Thank you I too have got it.
Well, I have another query. How I can know the current bet price and position? If I apply it on the browser then can the API tell me where exactly is my bid placed? This time I do not know the Bet ID or time?
Can you guide me for that?

**Comment by Lu-Yi-Hsun** [comment]
Digital?

**Comment by JafferWilson** [comment]
I mean binary or digital any of these. Especially if possible then binary first.

**Comment by Lu-Yi-Hsun** [comment]
so you want binary option "position" ?
yes i have skype

**Comment by JafferWilson** [comment]
Thank you @Lu-Yi-Hsun This is solved... :)
