### ISSUE TITLE
cant get canldes

### ISSUE THREAD

**Issue by suddar** [Lu-Yi-Hsun/iqoptionapi#5]
Here my code to get candles_data:
api.get_candles(1, 60, 1, api.api.timesync.server_timestamp)

But it failed  
Log: fail get_candles need reconnect

**Comment by Lu-Yi-Hsun** [comment]
import time
i change All active to name
 1->"EURUSD"  
more clear
```
api.get_candles("EURUSD", 60, 1, time.time())
```
