### ISSUE TITLE
Cannot get candles from IQoptoon

### ISSUE THREAD

**Issue by jimmylai-hk** [Lu-Yi-Hsun/iqoptionapi#68]
I'm able to setup the connection with IQoption using the code below.

con=IQ_Option(email,password)
con.set_max_reconnect(5)

Below is the message that I have print the connection.
<iqoptionapi.stable_api.IQ_Option object at 0x0000000008C52E10>

and then I run the following simple code.

candle = con.get_candles("EURUSD-OTC", 60,2,time.time)

Below is the error message. (part of the error message only)

ERROR:root:**error** get_candles need reconnect
DEBUG:iqoptionapi.api:https://auth.iqoption.com/api/v1.0/login
DEBUG:iqoptionapi.api:<Response [200]>
DEBUG:iqoptionapi.api:{"data":{"ssid":"d8316ddc36fa9ee954d4b63a282cf9ba"}}
DEBUG:iqoptionapi.api:{'Server': 'nginx', 'Date': 'Fri, 11 Jan 2019 23:42:57 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '52', 'Connection': 'keep-alive', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Accept, Accept-Language, Content-Type, YourOwnHeader', 'Access-Control-Allow-Methods': 'POST, GET, OPTIONS, PUT, DELETE', 'Access-Control-Allow-Origin': '*', 'Set-Cookie': 'ssid=d8316ddc36fa9ee954d4b63a282cf9ba; Path=/; Domain=iqoption.com; Max-Age=2592000; Secure', 'Strict-Transport-Security': 'max-age=15555600', 'X-Content-Type-Options': 'nosniff'}
DEBUG:iqoptionapi.api:<RequestsCookieJar[<Cookie ssid=d8316ddc36fa9ee954d4b63a282cf9ba for .iqoption.com/>]>
DEBUG:iqoptionapi.ws.client:Websocket client connected.
DEBUG:iqoptionapi.api:{"name": "ssid", "msg": "d8316ddc36fa9ee954d4b63a282cf9ba"}

The above code work before.....but I dont know why the code cannot work now.  Any clues?

**Comment by Lu-Yi-Hsun** [comment]
@jimmylai-hk
Websocket-client version?
Python version?

**Comment by Lu-Yi-Hsun** [comment]
@jimmylai-hk
```python
from iqoptionapi.stable_api import IQ_Option
import time
con = IQ_Option(email, password)
candle = con.get_candles("EURUSD-OTC",60,2,time.time())
                                                                             #^^^ the bug: not "time.time"
print(candle)
```

**Comment by jimmylai-hk** [comment]
Many thx for your quick respond.

It's my typo in my previous message.

Indeed, my code is 

candle = con.get_candles("EURUSD-OTC",60,2,time.time())

and still got the same error.

I have no issue in the past using the same code.

**Comment by Lu-Yi-Hsun** [comment]
@jimmylai-hk  
websocker-client version:
python version:
operation system:

**Comment by jimmylai-hk** [comment]
import websocket
print(websocket.__version__)

0.47.0

**Comment by jimmylai-hk** [comment]
Python version: ['3.6.7 |Anaconda, Inc.| (default, Oct 28 2018, 19:44:12) [MSC v.1915 64 bit (AMD64)]']
dist: ('', '', '')
linux_distribution: ('', '', '')
system: Windows
machine: AMD64
platform: Windows-7-6.1.7601-SP1

**Comment by Lu-Yi-Hsun** [comment]
use this code ,and give me the log
```python
from iqoptionapi.api import IQOptionAPI
import iqoptionapi.constants as OP_code
import logging
logging.basicConfig(level=logging.DEBUG,format='%(asctime)s %(message)s')
import time
api=IQOptionAPI("iqoption.com", "email","password")
api.connect()
api.getcandles(OP_code.ACTIVES["EURUSD-OTC"], 60,2,time.time())
while api.candles.candles_data==None:
    pass
print(api.candles.candles_data)
```

**Comment by jimmylai-hk** [comment]
It work now.  Many thanks.

**Comment by Lu-Yi-Hsun** [comment]
@jimmylai-hk  that is low level code.

so you can work on height level code?
