### ISSUE TITLE
403 Forbidden nginx

### ISSUE THREAD

**Issue by rodrigho** [Lu-Yi-Hsun/iqoptionapi#7]
Since yesterday I have been getting this error:

DEBUG:iqoptionapi.api:{'Server': 'nginx', 'Content-Length': '162', 'Date': 'Thu, 03 May 2018 04:51:55 GMT', 'Content-Type': 'text/html', 'Connection': 'keep-alive'}
DEBUG:iqoptionapi.api:<RequestsCookieJar[]>
ERROR:root:fail connect()
DEBUG:iqoptionapi.api:https://iqoption.com/api/login
DEBUG:iqoptionapi.api:<Response [403]>
DEBUG:iqoptionapi.api:<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

I can not connect to the iqoption api
Could you help me with this?

**Comment by Lu-Yi-Hsun** [comment]
please update last version

 i fix it
