### ISSUE TITLE
getprofile route isnt workin

### ISSUE THREAD

**Issue by virgincodes** [Lu-Yi-Hsun/iqoptionapi#71]
hey dude appreciate the API i really do but some bugs are making it quite hard to use the example the login route which i managed to fix and the getprofile route which i can't fix

**Comment by Lu-Yi-Hsun** [comment]
@virgincodes Give me Sample code,log file

**Comment by virgincodes** [comment]
DEBUG:iqoptionapi.ws.client:{"name":"front","msg":"ws10b"}
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1548496525632}
DEBUG:iqoptionapi.ws.client:{"name":"heartbeat","msg":1548496525632}
DEBUG:iqoptionapi.api:{"msg": {"msg": {"userTime": 1548496525000,
"heartbeatTime": 1548496525632}}, "name": "heartbeat"}
DEBUG:iqoptionapi.api:https://api.iqoption.com/api/getprofile
DEBUG:iqoptionapi.ws.client:{"name":"timeSync","msg":1548496526637}
DEBUG:iqoptionapi.api:<Response [404]>
DEBUG:iqoptionapi.api:404 page not found

**Comment by Lu-Yi-Hsun** [comment]
@virgincodes  ok i am try fix now

**Comment by Lu-Yi-Hsun** [comment]
@virgincodes  i test getprofile work well

test your version 3.6.

**Comment by virgincodes** [comment]
version 3.6

**Comment by Lu-Yi-Hsun** [comment]
@virgincodes Give me your sample code,.

I still can not rebuild your bug

**Comment by virgincodes** [comment]
dont get what u mean by that?

**Comment by virgincodes** [comment]
the post request to https://api.iqoption.com/api/getprofile on the api is  returning 404

**Comment by Lu-Yi-Hsun** [comment]
@virgincodes 
give me your python code.

in last version is request https://iqoption.com/api/getprofile

**Comment by virgincodes** [comment]
OK THAT worked but the thing is that when i tried using  https://iqoption.com/api/login it didnt work i had to get in the code and change the host to https://auth.iqoption.com/api/v1.0/login so it could work and that affected every routh

**Comment by Lu-Yi-Hsun** [comment]
@virgincodes 
i think you work on old version.
because last version is login:https://auth.iqoption.com/api/v1.0/login
                                      getprofile:https://iqoption.com/api/getprofile

**Comment by Lu-Yi-Hsun** [comment]
try this code
```python
import time
from iqoptionapi.stable_api import IQ_Option
I_want_money=IQ_Option("email","password")
goal="EURUSD"
print("get candles")
print(I_want_money.get_candles(goal,60,111,time.time()))
```

**Comment by virgincodes** [comment]
giving me the same error

**Comment by virgincodes** [comment]
wait i think ive seen my error it was created by me thinkering let me unisntall and reinstall and i would get back to u man thanks alot

**Comment by Lu-Yi-Hsun** [comment]
so iqoptionapi can work now?

**Comment by virgincodes** [comment]
awesome man it works thanks
