### ISSUE TITLE
[SUGGESTION] use git tags to version control to avoid problems with breaking changes

### ISSUE THREAD

**Issue by rrfaria** [Lu-Yi-Hsun/iqoptionapi#72]
Hi @Lu-Yi-Hsun 

thanks for keeping this Api updated 

I would suggest you to each time there is a release a new version like you did in past 
make a new tag version on git 

It helps because if there is something breaking change it will not broke any implementation with another version.

For instance: I'm using version 3.5 and you has already release version 3.6 if I update it may broke my app. I know it will not but in future versions could do it.

maybe you could use gitflow to control your development.

this tool works very well controling version automatically
take a look:
To linux:

https://github.com/petervanderdoes/gitflow-avh/wiki/Installing-on-Linux,-Unix,-etc.

To mac:
https://github.com/petervanderdoes/gitflow-avh/wiki/Installing-on-Mac-OS-X

to windows
https://github.com/petervanderdoes/gitflow-avh/wiki/Installing-on-Windows

**Comment by Lu-Yi-Hsun** [comment]
@rrfaria Thank SUGGESTION

update here: https://github.com/Lu-Yi-Hsun/iqoptionapi/releases ?

**Comment by rrfaria** [comment]
Thanks is exactly it ... it helps a lot
