### ISSUE TITLE
Trigger when a new binary option is opened

### ISSUE THREAD

**Issue by mdn522** [Lu-Yi-Hsun/iqoptionapi#75]
How do I get instant callback when a new option is opened from somewhere else

**Comment by Lu-Yi-Hsun** [comment]
read document first and try this 

https://github.com/Lu-Yi-Hsun/iqoptionapi#get_optioninfo

**Comment by mdn522** [comment]
With this function I have to manually check for opened binary options. 
Is there any way that the server will send message when there is a new binary option opened?

**Comment by Lu-Yi-Hsun** [comment]
you need to poll check is a new binary option
