### ISSUE TITLE
Error in Digital Buy 

### ISSUE THREAD

**Issue by remymatheus** [Lu-Yi-Hsun/iqoptionapi#78]
Hi, thanks for your work, when i try buy a digital option with the sample code launch a this error: 

Traceback (most recent call last):
  File "test3.py", line 26, in <module>
    buy_check,id=I_want_money.buy_digital(amount,instrument_id)
  File "/usr/local/lib/python3.5/dist-packages/iqoptionapi/stable_api.py", line 665, in buy_digital
    stop_lose_price=0, take_profit_price=0)
TypeError: buy_order() got an unexpected keyword argument 'stop_lose_price'

**Comment by Lu-Yi-Hsun** [comment]
@remymatheus  thank find this bug ,i will fix that quickly

**Comment by Lu-Yi-Hsun** [comment]
@remymatheus 
version 3.6.2 fix

**Comment by remymatheus** [comment]
Thanks for your reply, i have other question about buy digital options, how i can buy digital option sending the current price as parameter, like i buy a digital option when i click in the app, is not necessary el id_instrument. I do not know if I made myself understood, sorry for my bad English.
