### ISSUE TITLE
Fail to get results

### ISSUE THREAD

**Issue by suddar** [Lu-Yi-Hsun/iqoptionapi#8]
Hello Lu-Yi-Hsun, my tests often fail to get results.
Error log: 'Check_win time late 120sec'

**Comment by suddar** [comment]
I think api buy v2 has changed.

![39572414-4702e972-4ef9-11e8-84aa-14a52b871f5b](https://user-images.githubusercontent.com/37994239/39572504-9210c0c4-4ef9-11e8-893a-03f76c44822b.png)

**Comment by Lu-Yi-Hsun** [comment]
ok  i will fix

**Comment by Lu-Yi-Hsun** [comment]
@suddar  fix
