### ISSUE TITLE
ERROR:root:check buy_successful time late 60sec

### ISSUE THREAD

**Issue by qweasdzxc4321** [Lu-Yi-Hsun/iqoptionapi#83]
Hello, how do I prevent this error from happening? It only happens sometimes 
This is the code I am using
`
ACTIVES="EURUSD"
ACTION="call"#or "put"
expirations_mode=2
force_buy= False#i suggest use False
I_want_money.buy(Money,ACTIVES,ACTION,expirations_mode,force_buy)`

**Comment by Lu-Yi-Hsun** [comment]
@qweasdzxc4321 

if "IQOPTION server" not return "buy_successful" the buy() function wait until 60 sec

**Comment by qweasdzxc4321** [comment]
thank you
