### ISSUE TITLE
Could you add a withdraw feature?

### ISSUE THREAD

**Issue by markgacoka** [Lu-Yi-Hsun/iqoptionapi#87]
I was wondering if you could add an option to withdraw the amount to the options provided: Online wallet, webmoney and credit card. I would highly appreciate it.
I saw this code for the details brought back by the IQOption server in the code that you forked {"min":2,"max":1000000},"withdraw":
Could it be done? https://github.com/n1nj4z33/iqoptionapi/issues/92

**Comment by Lu-Yi-Hsun** [comment]
Why do you need your robot to withdraw your money?

I think withdraw money by your hand ,is more safe.

**Comment by markgacoka** [comment]
Ok. I agree. I was just thinking of full automation.
