### ISSUE TITLE
create a sample bot

### ISSUE THREAD

**Issue by tahmi123** [Lu-Yi-Hsun/iqoptionapi#9]
hey man would be nice if you created a simple sample bot that trades on patterns

**Comment by Lu-Yi-Hsun** [comment]
@tahmi123
Ok how about create random robot haha... It is simple and it will be Lose money.

for now short time option is hard to predict by neural networks MLP...

**Comment by tahmi123** [comment]
I mean something like this github.com/arun-mansa/tradingbot

**Comment by Salleyi75** [comment]
ok before the login problem happened, i was using the function and stuff in the normal iqoption.api module, do i have to use the new stableapi module you included when using this version for the everything to work or i can still use the normal iqoption.api module and everything will be fine?

**Comment by Lu-Yi-Hsun** [comment]
You can try 
1.
normal.iqoption.api ,I add some thing and fix some thing in there ,
2.
stable api is base on api,I am write document 

I think your old code

**Comment by Salleyi75** [comment]
Okay, thanks @Lu-Yi-Hsun

**Comment by Lu-Yi-Hsun** [comment]
@tahmi123 
what your robot mean? sorry i am not understand

**Comment by tahmi123** [comment]
Yeah I know but I have no idea how to begin, I was using one by Arun Kumar and he hasn't been updated so I can't use that anymore, github.com/arun-mansa/tradingbot

**Comment by Lu-Yi-Hsun** [comment]
@tahmi123
First you need to 

1.login
2.get candles/real time candles
3.analysis candles
4.buy your answer..
5. Loop to 2.
