### ISSUE TITLE
Pairs Binary or Digital

### ISSUE THREAD

**Issue by lucasmuniz** [Lu-Yi-Hsun/iqoptionapi#90]
Hi.
Please, how can I select Digital pairs and not Binary pairs?

![Capturar](https://user-images.githubusercontent.com/7372442/58608441-eff56000-8279-11e9-855d-2f45ffca0895.PNG)

**Comment by Lu-Yi-Hsun** [comment]
@lucasmuniz 
https://github.com/Lu-Yi-Hsun/iqoptionapi#for-digital

**Comment by lucasmuniz** [comment]
@Lu-Yi-Hsun 

Why this example use random?

I did many tests and I noticed when the 'profit' is none, there is an error in IQ Option and the operation does not be created, maybe it is not the best practice, or is it only a example?

**Comment by Lu-Yi-Hsun** [comment]
Yes It is only a example , if profit is none, you can not buy ‘EURUSD” on that price, so you need to choose other

**Comment by lucasmuniz** [comment]
How do buy at the actual price?

Using random or selecting one price, happens it

![Capturar3](https://user-images.githubusercontent.com/7372442/58672992-cf7fe100-831f-11e9-8b35-7b343689d840.PNG)

**Comment by Lu-Yi-Hsun** [comment]
That is digit 

So you can buy many difference price for difference profit.

You can get real-time candle to check the price

**Comment by lucasmuniz** [comment]
> @lucasmuniz That is digit
> 
> So you can buy many difference price for difference profit.
> 
> You can get real-time candle to check the price

Sorry, but when i create de instument_id with the actual price, i received the error below

![Capturar4](https://user-images.githubusercontent.com/7372442/58848526-57862380-865d-11e9-88ee-f940c15d180d.PNG)

I think this is not right

**Comment by Lu-Yi-Hsun** [comment]
Ok I will check what happen

**Comment by Lu-Yi-Hsun** [comment]
@lucasmuniz
i test the code,it can work great!

when you buy the profit:None
you will get error

**Comment by Lu-Yi-Hsun** [comment]
> > @lucasmuniz That is digit
> > So you can buy many difference price for difference profit.
> > You can get real-time candle to check the price
> 
> Sorry, but when i create de instument_id with the actual price, i received the error below
> 
> ![Capturar4](https://user-images.githubusercontent.com/7372442/58848526-57862380-865d-11e9-88ee-f940c15d180d.PNG)
> 
> I think this is not right

i think digit is change fast.
example
when you want to buy price "1.26",but digit price is change fast .you can not buy "1.26" anymore

**Comment by lucasmuniz** [comment]
I think the buy is successed when the price is in the strike list ... :(

**Comment by Lu-Yi-Hsun** [comment]
strike list is change very fast,so i think it is possible the price is change

**Comment by lucasmuniz** [comment]
I don't know, because i tried many times, but none completed.

I think it has another way without informing price, as it is done in binaries, what do you think?

**Comment by Lu-Yi-Hsun** [comment]
That code,I can completed some option.

I will check “digital “ how to improve that

**Comment by lucasmuniz** [comment]
any news?

**Comment by Lu-Yi-Hsun** [comment]
@lucasmuniz  https://github.com/Lu-Yi-Hsun/iqoptionapi#buy_digital_spot

it can buy  actual price

**Comment by aylonMuramatsu** [comment]
@Lu-Yi-Hsun 

The spot is not working is displaying "error" is there a solution?

NOTE: Congratulations on the project, you are very talented

**Comment by lucasmuniz** [comment]
@Lu-Yi-Hsun thank you!!!!
