### ISSUE TITLE
Get candle fail

### ISSUE THREAD

**Issue by guilhersantos** [Lu-Yi-Hsun/iqoptionapi#91]
I got this code on [youtube](https://www.youtube.com/watch?v=rIKt04DlXP0) and it works fine, but the candles do not update.
Is it an error in the code or has IQOPTION changed anything?

from iqoptionapi.stable_api import IQ_Option

import numpy as np
import matplotlib.pyplot as plt 
import matplotlib.animation as anime
from mpl_finance import candlestick_ohlc
import time
import logging
logging.basicConfig(level=logging.DEBUG,format='%(asctime)s %(message)s')

binary = IQ_Option("email","login")
fig = plt.figure()
ax1 = plt.subplot2grid((1 ,1), (0, 0))

def movingaverage(value, window):
    weights = np.repeat(1.0, window)/window
    smas = np.convolve(value, weights, 'valid')
    return smas

def animate(i):
    ohlc = []
    ohlc_index = 1
    end_from_time = time.time()
    data_option = binary.get_candles('EURUSD', 15, 100, end_from_time)

    for data_ohlc in data_option:
        data_me = ohlc_index, data_ohlc['open'], data_ohlc['max'], data_ohlc['min'], data_ohlc['close'], data_ohlc['volume']
        ohlc.append(data_me)
        ohlc_index += 1
    
    ax1.clear()
    plt.xlabel('time')
    plt.ylabel('Price')
    plt.title('EURUSD')
    ax1.grid(True)
    candlestick_ohlc(ax1, ohlc, width=0.7, colorup='g', colordown='r')

ani = anime.FuncAnimation(fig, animate, interval=5000)
plt.show()

**Comment by Lu-Yi-Hsun** [comment]
@guilhersantos

 ! holiday Only support “EURUSD-OTC”

Not “EURUSD”

**Comment by guilhersantos** [comment]
thanks bro!
